### PR TITLE
fix:Replace the link preview library 

### LINKED ISSUE #1440: Remove the Link preview library and add another instead of it
**Actual Behaviour**

Currently there is link preview library present in the app that is used to preview the images in the links etc, but this library is  not acceptable by FDroid. 
Check issue #1302 

**Expected Behaviour**

Remove the link preview library and find an alternative to the library.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #1440  

Parent issue : #1302

Changes: Removed the link preview library that was already present and added an alternative library that can be acceptable for FDroid.

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 1]
```diff
@@ -262,8 +269,10 @@ public void onPos(final SourceContent sourceContent, boolean b) {
             if (!(url.toString().startsWith(http.toString()) || url.toString().startsWith(https.toString()))) {
                 url = http.append(url.toString());
             }
-            TextCrawler textCrawler = new TextCrawler();
-            textCrawler.makePreview(linkPreviewCallback, url.toString());
+
+            richPreview.getPreview(String.valueOf(url));
+            // /TextCrawler textCrawler = new TextCrawler();
```
Comment (codedsun) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: They can be removed !

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 2]
```diff
@@ -77,6 +77,7 @@
     private Realm realm;
     private String url;
     private ChatMessage model;
+    private MetaData data;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Why the need to save this?

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 3]
```diff
@@ -208,34 +208,34 @@ public void onClick(View view) {
             RichPreview richPreview = new RichPreview(new ResponseListener() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Also, this is a memory leak

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java (hunk 2 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: in the previous implementation and android studio showed errors and asked to convert it into a array element

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Why do you need to store it globally?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: same as above, it is inside a function and on declaring it in the function, android studio forces it to make a final array element

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: That doesn't answer it. Why are you storing it globally, why do you need it outside the scope

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 4]
```diff
@@ -378,4 +330,62 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
 
         });
     }
+
+    private void setResponseListener(final Context currContext) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Remove context as parameter and return the listener rather than having void function

**Comment by batbrain7** [comment]
@iamareebjamal done the changes

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 5]
```diff
@@ -331,9 +331,9 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
         });
     }
 
-    private void setResponseListener(final Context currContext) {
+    private ResponseListener setResponseListener() {
 
-        responseListener = new ResponseListener() {
+        return responseListener = new ResponseListener() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No need of `responseListener = `

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 6]
```diff
@@ -203,7 +203,7 @@ public void onClick(View view) {
             titleTextView.setVisibility(View.GONE);
             previewLayout.setVisibility(View.GONE);
 
-            setResponseListener(currContext);
+            responseListener = setResponseListener();
             RichPreview richPreview = new RichPreview(responseListener);
             responseListener = null;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No need of this, what will setting this null do?

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 7]
```diff
@@ -378,4 +330,62 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
 
         });
     }
+
+    private ResponseListener setResponseListener() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: This method is not setting response listener

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 8]
```diff
@@ -378,4 +330,62 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
...
+
+                        final String imageLink = data.getImageurl();
+
+                        if (imageLink == null || imageLink.equals("")) {
+                            previewImageView.setVisibility(View.GONE);
+                            link.setImageURL("");
+                        } else {
+                            previewImageView.setVisibility(View.VISIBLE);
+                            Picasso.with(itemView.getContext()).load(imageLink)
+                                    .fit().centerCrop()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: load, centerCrop on each line

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 9]
```diff
@@ -378,4 +330,62 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
 
         });
     }
+
+    private ResponseListener setResponseListener() {
+
+        return responseListener = new ResponseListener() {
+            @Override
+            public void onData(MetaData data) {
+                if (!PrefManager.hasTokenExpired() || PrefManager.getBoolean(Constant.ANONYMOUS_LOGGED_IN, false)) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Instead of nesting if, do early return

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 10]
```diff
@@ -378,4 +330,62 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
...
+                    realm.beginTransaction();
+                    Realm realm = Realm.getDefaultInstance();
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: You began a transaction and then got a new instance of Realm?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: @iamareebjamal this was the previous code that was already present I just shifted it to a new function, I will work upon it now

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java (hunk 6 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: @iamareebjamal since there was no method to stop the listener won't setting it null help in avoiding memory leaks ?

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java (hunk 10 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No, let it be. Just handle the changes above

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java (hunk 9 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Let this one be as well

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java (hunk 6 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No, There must be a method in richPreview to remove listener

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: @iamareebjamal there is no method to remove the listener

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Done the changes @iamareebjamal

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 11]
```diff
@@ -378,4 +330,64 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
 
         });
     }
+
+    private ResponseListener initResponseListener() {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: getRrsponseListener

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 12]
```diff
@@ -77,6 +78,7 @@
     private Realm realm;
     private String url;
     private ChatMessage model;
+    private ResponseListener responseListener;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No need of storing listener now, or if there is not null value, then don't reinitialize it again

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 13]
```diff
@@ -262,8 +214,8 @@ public void onPos(final SourceContent sourceContent, boolean b) {
             if (!(url.toString().startsWith(http.toString()) || url.toString().startsWith(https.toString()))) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: There are toString so many times, use once and store and use string value ahead

File: app/build.gradle [hunk 14]
```diff
@@ -99,10 +99,8 @@ dependencies {
     implementation "com.squareup.okhttp3:logging-interceptor:${rootConfiguration.okHttpVersion}"
 
     //For Link Previews
-    implementation "org.jsoup:jsoup:${rootConfiguration.jsoupVersion}"
-
-    // required
-    implementation "com.leocardz:link-preview:${rootConfiguration.linkPreviewVersion}"
+    implementation "org.jsoup:jsoup:${rootConfiguration.jsoupVersion}" // required
```
Comment (iamareebjamal) [inline app/build.gradle]: Remove

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 15]
```diff
@@ -378,4 +330,64 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
...
+                        }
+
+                        link.setBody(data.getDescription());
+                        link.setHeadline(data.getTitle());
+                        link.setUrl(data.getUrl());
+                        url = data.getUrl();
+
+                        final String imageLink = data.getImageurl();
+
+                        if (imageLink == null || TextUtils.isEmpty(imageLink)) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: No need to check == null

File: app/build.gradle (hunk 14 above)
Comment (batbrain7) [reply app/build.gradle]: @iamareebjamal the library requires the use of jsoup, Initially I removed it but then I saw in the code of the library that there was the usage of jsoup so it was needed.

Comment (iamareebjamal) [reply app/build.gradle]: Alright

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 16]
```diff
@@ -197,73 +198,24 @@ public void onClick(View view) {
...
+            String url = urlList.get(0);
+            String http = "http://";
+            String https = "https://";
+            if (!(url.startsWith(http) || url.startsWith(https))) {
+                url = http + url;
             }
-            TextCrawler textCrawler = new TextCrawler();
-            textCrawler.makePreview(linkPreviewCallback, url.toString());
+
+            richPreview.getPreview(String.valueOf(url));
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: url is already String

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 17]
```diff
@@ -197,73 +198,24 @@ public void onClick(View view) {
...
-            StringBuilder url = new StringBuilder(urlList.get(0));
-            StringBuilder http = new StringBuilder("http://");
-            StringBuilder https = new StringBuilder("https://");
-            if (!(url.toString().startsWith(http.toString()) || url.toString().startsWith(https.toString()))) {
-                url = http.append(url.toString());
+            String url = urlList.get(0);
+            String http = "http://";
+            String https = "https://";
+            if (!(url.startsWith(http) || url.startsWith(https))) {
+                url = http + url;
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Default to https

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 18]
```diff
@@ -378,4 +330,64 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
 
         });
     }
+
+    private ResponseListener getResponseListener() {
+
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Extra line

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 19]
```diff
@@ -378,4 +330,64 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
...
+            @Override
+            public void onData(MetaData data) {
+                if (!PrefManager.hasTokenExpired() || PrefManager.getBoolean(Constant.ANONYMOUS_LOGGED_IN, false)) {
+                    realm.beginTransaction();
+                    Realm realm = Realm.getDefaultInstance();
+                    WebLink link = realm.createObject(WebLink.class);
+
+                    if (data != null) {
+
+                        if (!data.getDescription().isEmpty()) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: TextUtils.isEmpty

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 20]
```diff
@@ -378,4 +330,64 @@ public void onFailure(Call<SkillRatingResponse> call, Throwable t) {
...
+                            Timber.d("onPos: %s", data.getDescription());
+                            previewLayout.setVisibility(View.VISIBLE);
+                            descriptionTextView.setVisibility(View.VISIBLE);
+                            descriptionTextView.setText(data.getDescription());
+                        }
+
+                        if (!data.getTitle().isEmpty()) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: TextUtils.isEmpty

**Comment by iamareebjamal** [comment]
@batbrain7 Last requirement of change

**Comment by batbrain7** [comment]
@iamareebjamal changes done

File: app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java [hunk 21]
```diff
@@ -197,73 +198,24 @@ public void onClick(View view) {
...
-                        }
-
-                        model.setWebLinkData(link);
-                        realm.copyToRealmOrUpdate(model);
-                        realm.commitTransaction();
-                    }
-                }
-            };
+            ResponseListener responseListener;
+            responseListener = getResponseListener();
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java]: Instead of

```Java
int a;
a = 5;
func(a*3);
```

Why not just 

```Java
func(15);
```

**Comment by batbrain7** [comment]
@iamareebjamal please merge
