### PR TITLE
fix: Handle menu items for fragments in activity

### LINKED ISSUE #1835: Search menu is displayed in skill details fragment
**Actual Behaviour**

Search menu is displayed in skill details fragment.

**Expected Behaviour**

Menu item should not be displayed.

**Screenshots of the issue**

<p align="center">
 
</p>

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #1835

### CODE REVIEW

**Comment by liveHarshit** [comment]
It is same as earlier for settings and about fragment. There was no search option in settings fragment.

File: app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt [hunk 1]
```diff
@@ -31,16 +30,6 @@ class AboutUsFragment : Fragment() {
         return rootView
     }
 
-    override fun onPrepareOptionsMenu(menu: Menu) {
-        val itemAbout = menu.findItem(R.id.menu_about)
-        itemAbout.isVisible = false
-        val itemSettings = menu.findItem(R.id.menu_settings)
-        itemSettings.isVisible = false
-        val searchoption = menu.findItem(R.id.action_search)
-        searchoption.isVisible = false
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt]: Search option was hidden in the fragment. And now it is same.

File: app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt [hunk 2]
```diff
@@ -219,16 +218,6 @@ class ChatSettingsFragment : PreferenceFragmentCompat(), ISettingsView {
         }
     }
 
-    override fun onPrepareOptionsMenu(menu: Menu) {
-        val itemSettings = menu.findItem(R.id.menu_settings)
-        itemSettings.isVisible = false
-        val itemAbout = menu.findItem(R.id.menu_about)
-        itemAbout.isVisible = false
-        val searchoption = menu.findItem(R.id.action_search)
-        searchoption.isVisible = false
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: Search option was hidden in the fragment. And now it is same.

**Comment by liveHarshit** [comment]
Please review
