### PR TITLE
Fix#1143 Enter as end working

### LINKED ISSUE #1143: Press 'enter' key to send not working
**Actual Behaviour**

Currently, the user cannot send the message by pressing the enter key on the keyboard even after turning on this feature from the settings.

**Expected Behaviour**

The user should be able to send message by pressing the enter key on the keyboard if s/he chooses to do so in the app settings.

**Screenshots of the issue**

tap_enter_to_send

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1143 Debugged the check of enter key press and made it working

Changes: Added listener

Screenshots for the change: 

@iamareebjamal @batbrain7 @arundhati24 Check this!

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 1]
```diff
@@ -112,6 +115,7 @@ class ChatActivity : AppCompatActivity(), IChatView {
     }
 
     private fun setEditText() {
+        enterAsSend = PrefManager.getBoolean(Constant.ENTER_SEND, false)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: Rather than getting it again and again, use lazy property

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 2]
```diff
@@ -163,6 +167,18 @@ class ChatActivity : AppCompatActivity(), IChatView {
             }
             handled
         })
+
+        askSusiMessage.setOnKeyListener(View.OnKeyListener { view, i, keyEvent ->
+            if (i == KeyEvent.KEYCODE_ENTER && enterAsSend && (keyEvent.action == KeyEvent.ACTION_UP || keyEvent.action == KeyEvent.ACTION_DOWN)) {
+                val message = askSusiMessage.text.toString().trim({ it <= ' ' })
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: So, are we disallowing sending only spaces as messages?

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: @iamareebjamal Yes! as earlier method did

**Comment by codedsun** [comment]
@iamareebjamal Check now!

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 3]
```diff
@@ -166,6 +171,18 @@ class ChatActivity : AppCompatActivity(), IChatView {
             }
             handled
         })
+
+        askSusiMessage.setOnKeyListener(View.OnKeyListener { view, i, keyEvent ->
+            if (i == KeyEvent.KEYCODE_ENTER && enterAsSend.value && (keyEvent.action == KeyEvent.ACTION_UP || keyEvent.action == KeyEvent.ACTION_DOWN)) {
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: break the statement and add in second line

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 4]
```diff
@@ -61,6 +63,9 @@ class ChatActivity : AppCompatActivity(), IChatView {
     private lateinit var progressDialog: ProgressDialog
     private var example: String = ""
     private var isConfigurationChanged = false
+    private var enterAsSend = lazy{
+        PrefManager.getBoolean(Constant.ENTER_SEND, false)
+    }
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: by lazy and add space after lazy

**Comment by codedsun** [comment]
@iamareebjamal chck now!

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 5]
```diff
@@ -61,6 +63,9 @@ class ChatActivity : AppCompatActivity(), IChatView {
     private lateinit var progressDialog: ProgressDialog
     private var example: String = ""
     private var isConfigurationChanged = false
+    private var enterAsSend = lazy {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: by lazy

**Comment by codedsun** [comment]
@iamareebjamal Check please 👍
