### PR TITLE
fix: Terms &  condition of signup page link to Privacy fragment

### LINKED ISSUE #2057: Change the link of terms and condition in sign up page to privacy fragment
**Describe the feature you'd like**
Change the intent of terms and conditions in sign up page to privacy fragment. Currently it passes an intent which opens the privacy page present at the website. 

**Additional context**
We should change it now as we have the privacy fragment added in the app. 

**Screenshots**
Screenshot_2019-03-22-16-24-09-456_ai susi

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2057 

Changes: 
* Pass an intent to Call the SkillsActivity with an extra parameter
* Made a check of the incoming intent in the onCreate of SkillsActivity to check which fragment to open.

Screenshots for the change: 
privacyHyperlink

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt [hunk 1]
```diff
@@ -212,7 +212,9 @@ class SignUpActivity : AppCompatActivity(), ISignUpView {
 
     private fun signUpToTermsConditionPage() {
         signUpToTermsCondition.setOnClickListener {
-            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://chat.susi.ai/privacy")))
+            val intent = Intent(this@SignUpActivity, SkillsActivity::class.java)
+            intent.putExtra("fromWhere", 1)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: What is one?

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: Sir, I have used one as a parameter value to tell the SkillsActivity that the call is from SignUpActivity and it should open Privacy Fragment instead of SkillsFragment. I used it as a techniques to open fragment of an activity from another activity.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: Use proper naming conventions and extract in a constant

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 2]
```diff
@@ -60,7 +61,9 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
         settingsPresenter = SettingsPresenter(this)
         val skillFragment = SkillListingFragment()
         val privacyFragment = PrivacyFragment()
-        if (intent.getIntExtra("fromWhere", 0) == 1) {
+        val bundle = intent.extras
+        val intentValue = bundle?.getBoolean(Constant.FROM_SIGN_UP_ACTIVITY)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Name variable appropriately

**Comment by atm1504** [comment]
@iamareebjamal please check it now

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 3]
```diff
@@ -61,15 +62,25 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
         settingsPresenter = SettingsPresenter(this)
         val skillFragment = SkillListingFragment()
-        //skills = skillFragment.skills
-        supportFragmentManager.beginTransaction()
-                .add(R.id.fragment_container, skillFragment, TAG_SKILLS_FRAGMENT)
-                .addToBackStack(TAG_SKILLS_FRAGMENT)
-                .commit()
+        val privacyFragment = PrivacyFragment()
+        val bundle = intent.extras
+        val intentValue = bundle?.getBoolean(Constant.SIGN_UP_TO_PRIVACY)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: What intentValue. I don't understand the name of this variable

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Sir, this is a situation where we are trying to open a fragment that is contained inside another activity. The other activity doesn't have the default fragment as the one that we require. And we know that we cannot open the fragment of another activity directly until it is the default fragment of that activity. So here along with the intent I am passing the parameter that I have called the activity from Signup page. It should open the Privacy fragment instead of SkillsListingFragment(the default fragment of this activity).

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: I'm talking about using a sensible variable name

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Sir, I am sorry for that. I am changing that variable name to an appropriate one.

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 4]
```diff
@@ -64,8 +64,8 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
         val skillFragment = SkillListingFragment()
         val privacyFragment = PrivacyFragment()
         val bundle = intent.extras
-        val intentValue = bundle?.getBoolean(Constant.SIGN_UP_TO_PRIVACY)
-        if (intentValue == true) {
+        val intentPassedFromSignUpActivity = bundle?.getBoolean(Constant.SIGN_UP_TO_PRIVACY)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Still a poorly named variable.

Do you name your variables like
```
int integer = 4;
long aLongDefinedByMe = 6;
```

or 

```
int age = 20;
long courseId = 3456;
```

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 5]
```diff
@@ -61,15 +62,25 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
         settingsPresenter = SettingsPresenter(this)
         val skillFragment = SkillListingFragment()
-        //skills = skillFragment.skills
-        supportFragmentManager.beginTransaction()
-                .add(R.id.fragment_container, skillFragment, TAG_SKILLS_FRAGMENT)
-                .addToBackStack(TAG_SKILLS_FRAGMENT)
-                .commit()
+        val privacyFragment = PrivacyFragment()
+        val bundle = intent.extras
+        val intentValueSignUpToPrivacy = bundle?.getBoolean(Constant.SIGN_UP_TO_PRIVACY)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]:
```suggestion
        val toPrivacy = bundle?.getBoolean(Constant.SIGN_UP_TO_PRIVACY)
```

File: app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt [hunk 6]
```diff
@@ -214,9 +214,9 @@ class SignUpActivity : AppCompatActivity(), ISignUpView {
 
     private fun signUpToTermsConditionPage() {
         signUpToTermsCondition.setOnClickListener {
-            val intent = Intent(this@SignUpActivity, SkillsActivity::class.java)
-            intent.putExtra(Constant.SIGN_UP_TO_PRIVACY, true)
-            startActivity(intent)
+            val intentToTermsCondition = Intent(this@SignUpActivity, SkillsActivity::class.java)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: Needless change

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: Sir, I didn't understand what changes you wanted in the last comment. Can you please clarify?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt]: Revert this to intent

**Comment by atm1504** [comment]
@iamareebjamal please review this also. I forgot to mention that I need this also to be merged to work with #2086

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 5 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Still not changed

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Sir, can you please suggest what name shall I give here?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: I already have, look above

**Comment by atm1504** [comment]
@iamareebjamal sir please check my latest commit. I hope this variable name is clearly mentioning the task it is performing.
