### PR TITLE
fix: tabletype responses are fetched from history

### LINKED ISSUE #1466: Table Response is not fetched while retrieving the chat history
**Actual Behaviour**

Null response is fetched for table-response queries when the response is fetched from the server, also the headings of the column should be bold.

**Expected Behaviour**

The table response should be mapped on receiving the data from the server, bold the column headings and the table card should be rounded.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #1466 

Changes: modified the parsing process of the table process, otherwise the data when fetched from the memory response returns null and then on clicking the thumbs up icon, the app crashes

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 1]
```diff
@@ -24,10 +25,12 @@ class ParseSusiResponseHelper {
     var webSearch = ""
     var stop = "Stopped"
     var isHavingLink = false
+    var tableData: TableDatas? = null
+    var count = 0;
 
     fun parseSusiResponse(susiResponse: SusiResponse, i: Int, error: String) {
 
-        actionType = susiResponse.answers[0].actions[i].type
+        actionType = susiResponse.answers[0].actions[i].type!!
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Not safe to use double exclamation.

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 2]
```diff
@@ -59,7 +62,7 @@ class ParseSusiResponseHelper {
             }
 
             Constant.STOP -> try {
-                stop = susiResponse.answers[0].actions[1].type
+                stop = susiResponse.answers[0].actions[1].type!!
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: same.

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 3]
```diff
@@ -78,6 +81,41 @@ class ParseSusiResponseHelper {
...
+                        val entry2 = iterator2?.next()
+                        count++
+                        for (count in 0..listColumn.size - 1) {
+                            val obj = listColumn.get(count)
+                            listTableData.add(entry2?.get(obj).toString())
+                        }
+                    }
+                    tableData = TableDatas(listColVal, listTableData)
+                }
+
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Extra line

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt [hunk 4]
```diff
@@ -17,16 +16,16 @@ class ParseTableSusiResponseHelper {
...
             var response1 = Gson().toJson(response)
-            var tableresponse = Gson().fromJson(response1, TableBody::class.java)
+            var tableresponse = Gson().fromJson(response1, Body::class.java)
 
             // to access the json elements of the response received
             // listColumn contains the key elements, listColVal contains the column name of the list
             // listTableData contains the data corresponding each of the key as extracted from the JSON,
             // it is the list of all the data elements in the answers of the JSON.
-            for (tableanswer in tableresponse.body.answers) {
+            for (tableanswer in tableresponse.body!!.answers) {
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt]: avoid using double exclamation

File: app/src/main/res/layout/table_recylcer_item.xml [hunk 5]
```diff
@@ -1,29 +1,28 @@
...
         android:layout_height="wrap_content"
-        android:id="@+id/column"
         android:padding="5dp"
-        android:textStyle="bold"
-        />
+        android:textColor="@color/md_black_1000"
+        android:textStyle="bold" />
+
     <TextView
+        android:id="@+id/data_item"
```
Comment (arundhati24) [inline app/src/main/res/layout/table_recylcer_item.xml]: Camel Case

File: app/src/main/res/layout/table_recylcer_item.xml [hunk 6]
```diff
@@ -1,29 +1,28 @@
...
         android:layout_width="wrap_content"
         android:layout_height="wrap_content"
         android:padding="@dimen/message_layout_margin"
-        android:visibility="gone"
-        android:id="@+id/data_item"
-        />
+        android:visibility="gone" />
+
     <TextView
+        android:id="@+id/data_item_link"
```
Comment (arundhati24) [inline app/src/main/res/layout/table_recylcer_item.xml]: Camel Case

Comment (batbrain7) [reply app/src/main/res/layout/table_recylcer_item.xml]: it is used with java file so not applicable

File: app/src/main/res/layout/table_recylcer_item.xml (hunk 5 above)
Comment (batbrain7) [reply app/src/main/res/layout/table_recylcer_item.xml]: used with java file

File: app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt [hunk 7]
```diff
@@ -15,7 +15,7 @@ class Answer {
 
     @SerializedName("data")
     @Expose
-    val data = RealmList<Datum>()
+    var data: List<Map<String, Any>>? = null
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt]: Convert to object

**Comment by batbrain7** [comment]
@iamareebjamal please review

File: app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt [hunk 8]
```diff
@@ -15,7 +15,7 @@ class Answer {
 
     @SerializedName("data")
     @Expose
-    var data: List<Map<String, Any>>? = null
+    var data: List<Map<String, Any>> = ArrayList()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt]: Object

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt]: @iamareebjamal android studio is not allowing using Object

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt]: Create a new class is what I mean

**Comment by batbrain7** [comment]
@iamareebjamal please review

File: app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt [hunk 9]
```diff
@@ -0,0 +1,6 @@
+package org.fossasia.susi.ai.rest.responses.susi
+
+class DataObject {
+
+    val data: List<Map<String, Any>> = ArrayList()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: The problem is `List<Map<String, Any>>`

**Comment by batbrain7** [comment]
@iamareebjamal I cannot break this into a serialised pojo because there are variable number of fields and variable keys and responses

File: app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt (hunk 9 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: @iamareebjamal I cannot break this into a serialised pojo because there are variable number of fields and variable keys and responses

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: First it was Datum, now it is Map of String and Any

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: the responses are fetched based on the action type and for the particular action type an implementation is done, for the table type the skills can be variable like "list of batman enemies" or "barcelona team players" these have different keys and values corresponding to them.

**Comment by batbrain7** [comment]
@iamareebjamal please review

File: app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt (hunk 9 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: But the Any part is cast to one of the Class at the end, right?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: Class here referring to a pojo?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: Yes

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: Any is used here because server may send an integer type data or a string type data, or a double and it depends to the skill made the type of response that will be sent by the server

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: So how do we know what data to be cast into when we display it to the user

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/DataObject.kt]: The response on being parsed is converted to string type and then passed to the adapter, so I changed Any to string and tested the apk it still works fine

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 10]
```diff
@@ -100,13 +100,13 @@ class ParseSusiResponseHelper {
                     }
                     val map2 = tableanswer.data
                     Timber.d(map2.toString())
-                    val iterator2 = map2?.iterator()
-                    while (iterator2?.hasNext().toString().toBoolean()) {
-                        val entry2 = iterator2?.next()
+                    val iterator2 = map2.iterator()
+                    while (iterator2.hasNext().toString().toBoolean()) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: iterator2.hasNext().toString().toBoolean().toString().toInt().toString().toBoolean()

Also, why not directly iterate via a forEach loop?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: while writing this I just went on with the while loop, is it more better using a for each loop ?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Yes

**Comment by batbrain7** [comment]
@iamareebjamal the forEach loop is added also please review and merge this PR so that we can get a stable release on the playstore

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 11]
```diff
@@ -78,6 +81,40 @@ class ParseSusiResponseHelper {
...
+                val listColumn: ArrayList<String> = ArrayList()
+                val listColVal: ArrayList<String> = ArrayList()
+                val listTableData: ArrayList<String> = ArrayList()
+
+                for (tableanswer in susiResponse.answers) {
+                    for (answer in tableanswer.actions) {
+                        val map = answer.columns
+                        val set = map?.entries
+                        val iterator = set?.iterator()
+                        while (iterator?.hasNext().toString().toBoolean()) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Still same

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 12]
```diff
@@ -78,6 +81,40 @@ class ParseSusiResponseHelper {
...
+                            val entry = iterator?.next()
+                            listColumn.add(entry?.key.toString())
+                            listColVal.add(entry?.value.toString())
+                        }
+                    }
+                    val map2 = tableanswer.data
+                    Timber.d(map2.toString())
+                    val iterator2 = map2.iterator()
+                    iterator2.forEach {
+                        val entry2 = iterator2.next()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Still same

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 13]
```diff
@@ -92,21 +92,19 @@ class ParseSusiResponseHelper {
                         val map = answer.columns
                         val set = map?.entries
                         val iterator = set?.iterator()
-                        while (iterator?.hasNext().toString().toBoolean()) {
-                            val entry = iterator?.next()
-                            listColumn.add(entry?.key.toString())
-                            listColVal.add(entry?.value.toString())
+                        iterator?.forEach {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: No iterator

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 14]
```diff
@@ -92,21 +92,19 @@ class ParseSusiResponseHelper {
...
+                            listColumn.add(it.key.toString())
+                            listColVal.add(it.value.toString())
                         }
                     }
                     val map2 = tableanswer.data
                     Timber.d(map2.toString())
                     val iterator2 = map2.iterator()
                     iterator2.forEach {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: No iterator

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt (hunk 13 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: @iamareebjamal should I use : 
```
set?.forEach {
      listColumn.add(it.key.toString())
      istColVal.add(it.value.toString())
       }
```

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt (hunk 14 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: similarly here : 
```
map2.forEach {
      count++
          for (count in 0..listColumn.size - 1) {
              val obj = listColumn.get(count)
               listTableData.add(it.get(obj).toString())
            }
      }
```

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt (hunk 13 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Yes

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 15]
```diff
@@ -78,6 +81,34 @@ class ParseSusiResponseHelper {
...
+            Constant.TABLE -> try {
+                count = 0
+                val listColumn: ArrayList<String> = ArrayList()
+                val listColVal: ArrayList<String> = ArrayList()
+                val listTableData: ArrayList<String> = ArrayList()
+
+                for (tableanswer in susiResponse.answers) {
+                    for (answer in tableanswer.actions) {
+                        val map = answer.columns
+                        map?.forEach {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Replace with answer.columns?.forEach

No need to create variables which are unused

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 16]
```diff
@@ -78,6 +81,34 @@ class ParseSusiResponseHelper {
                 Timber.e(e)
             }
 
+            Constant.TABLE -> try {
+                count = 0
+                val listColumn: ArrayList<String> = ArrayList()
+                val listColVal: ArrayList<String> = ArrayList()
+                val listTableData: ArrayList<String> = ArrayList()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: val anything = ArrayList<String>()

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 17]
```diff
@@ -78,6 +81,34 @@ class ParseSusiResponseHelper {
...
+                for (tableanswer in susiResponse.answers) {
+                    for (answer in tableanswer.actions) {
+                        val map = answer.columns
+                        map?.forEach {
+                            listColumn.add(it.key)
+                            listColVal.add(it.value.toString())
+                        }
+                    }
+                    val map2 = tableanswer.data
+                    map2.forEach {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: No need of map2 variable

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 18]
```diff
@@ -78,6 +81,34 @@ class ParseSusiResponseHelper {
...
+                        count++
+                        for (count in 0..listColumn.size - 1) {
+                            val obj = listColumn.get(count)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Foreach loop. This code looks like it's been written for C

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt [hunk 19]
```diff
@@ -14,13 +13,13 @@ class ParseTableSusiResponseHelper {
...
-    var count = 0;
+    var count = 0
 
     //parse the table response
-    fun parseSusiResponse(response: Response<TableSusiResponse>) {
+    fun parseSusiResponse(response: SusiResponse) {
         try {
             var response1 = Gson().toJson(response)
-            var tableresponse = Gson().fromJson(response1, TableBody::class.java)
+            var tableresponse = Gson().fromJson(response1, Body::class.java)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt]: Reuse Gson instance

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt (hunk 16 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: @iamareebjamal please suggest what should be done here

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt [hunk 20]
```diff
@@ -1,56 +0,0 @@
-package org.fossasia.susi.ai.chat
-
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseTableSusiResponse.kt]: Don't need this file , forgot to delete

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 21]
```diff
@@ -78,6 +82,31 @@ class ParseSusiResponseHelper {
...
+
+                susiResponse.answers.forEach {
+                    it.actions.forEach {
+                        it.columns?.forEach {
+                            listColumn.add(it.key)
+                            listColVal.add(it.value.toString())
+                        }
+                    }
+                    it.data.forEach {
+                        count++
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: No need of count

**Comment by batbrain7** [comment]
@iamareebjamal are there any further changes required in this PR?

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt [hunk 22]
```diff
@@ -65,19 +68,43 @@ class ParseSusiResponseHelper {
...
+                    it.actions.forEach {
+                        it.columns?.forEach {
+                            listColumn.add(it.key)
+                            listColVal.add(it.value.toString())
+                        }
+                    }
+                    it.data.forEach {
+                        listColumn.forEach { i ->
+                            String
+                            listTableData.add(it[i].toString())
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: This logic is strange to me, what is this doing?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: Consider an example of table type response, "Barcelona team players" this logic takes the column names first and then parses the blocks of data with the column keys and stores there value, here is the link for the response :https://api.susi.ai/susi/chat.json?timezoneOffset=-330&q=barcelona+team+players

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: OK, I am approving this but this needs serious refactoring and tests

**Comment by iamareebjamal** [comment]
@arundhati24 Review please

File: app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt (hunk 22 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt]: I understand @iamareebjamal. I will look into this

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt [hunk 23]
```diff
@@ -53,6 +53,7 @@ class ChatPresenter(chatActivity: ChatActivity) : IChatPresenter, IChatModel.OnR
     var backPressedOnce = false
     var id: Long = 0;
     var identifier: String = ""
+    var tableDatas: TableDatas? = null
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: data itself is a plural. Please change datas to data.

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: TableDatas is the name of the class and also if these changes don't matter a lot can we merge this PR as we are behind the release deadline

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: I don't know if it is right to use a non-existent word in dictionary to name a variable or a class. Once it gets merged nobody is going to change it, and it will stay there in the code.
@iamareebjamal If this is fine for you, then rest LGTM.

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: @arundhati24 as said above this bit needs refactoring and I said I will take care of them so these spell checks can be ignored, also naming variables is subjective if it looks good please approve and merge this PR.

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: @arundhati24 the TableData class is a different class and I don't know why is this such a big deal

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: Yes, TableDatas does not feel right, I'm going to say that you can continue to go with this if you send the refactoring PR today itself

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: Yes @iamareebjamal I will refactor PR by today
