### PR TITLE
Fixed #1339: Search bar appears in Settings

### LINKED ISSUE #1339: Seach bar from Skills Activity appear in Settings
**Actual Behaviour**

Searchbar and keyboard appears in the Settings screen, in a particular sequence.

**Expected Behaviour**

Search bar and keyboard should be closed

**Steps to reproduce it**

1. Tap on the Search icon in Skills Activity ,then the keyboard gets opened in the Skills Activity.
2. Tap on Settings, without doing anything else.
3. It takes us to the Settings page, but without closing the Keyboard and Search bar.

**Screenshots of the issue**

bug

**Would you like to work on the issue?**

Yes

EDIT: Happens for SkillDetails too

### PR DESCRIPTION
**Pull request by agh372**
Fixes #1339 

Changes: hid the keyboard and enabled the title before loading the fragment

@iamareebjamal @batbrain7 please review

### CODE REVIEW

**Comment by batbrain7** [comment]
@agh372 can you add a screenshot for the change?

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 1]
```diff
@@ -111,10 +116,9 @@ class SkillsActivity : AppCompatActivity() {
 
             action!!.setDisplayShowCustomEnabled(false) //disable a custom view inside the actionbar
             action.setDisplayShowTitleEnabled(true) //show the title in the action bar
-
             //add the search icon in the action bar
             mSearchAction?.icon = resources.getDrawable(R.drawable.ic_open_search)
-
+            hideKeyboard()
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: actually keyboard should not be hidden in the skill listing activity on clicking the cross button

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: handle this by hiding the keyboard on opening the about, settings and skill details and instead of adding handleMenuSearch() in these cases make another function that does this

Comment (agh372) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @batbrain7 changes are added, can you check?

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @agh372 no changes seen

**Comment by batbrain7** [comment]
@iamareebjamal @chiragw15 @arundhati24  please review
