### PR TITLE
Show appropriate message when there are no skills for a particular group (Fixed #1565)

### LINKED ISSUE #1565: Blank screen when there are no skills for a particular group
**Actual Behaviour**

A blank screen appears when there are no skills present in a group.

**Expected Behaviour**

Display a message to tell the user that no skills have been added for that particular group.

**Steps to reproduce it**

Open the skills listing page and click on "Connected Cars" group at the bottom of the page.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1565 

Changes: Now, a message 'No skills found' is displayed on the group wise skills listing fragment when there are no skills in a particular group.

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt [hunk 1]
```diff
@@ -73,6 +73,14 @@ class GroupWiseSkillsFragment : Fragment(), IGroupWiseSkillsView, SwipeRefreshLa
         progressSkillWait.visibility = if (boolean) View.VISIBLE else View.GONE
     }
 
+    override fun showEmptySkillsListMessage() {
+        if (activity != null) {
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: what if activity is not null?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: That's when this'll get executed

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: @batbrain7 Please have a look at this and see if this can be merged.

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: Actually I meant if it was null

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: If activity is null, this would never be called.

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt]: This would only be called if everything is fine, but a particular group has no skills yet i.e. no skills exist for that group yet.
