### PR TITLE
Fixes #410: Implemented number of messages to be deleted

### LINKED ISSUE #410: Display number of messages to be deleted before also in the alert dialog
**Actual Behaviour**

In most of the messaging apps if the user selects multiple messages to delete an alert dialog appears with displaying **Delete 2 or 3 messages?**. Currently it asks to delete it or not.

**Expected Behaviour**

Display the delete 2 or 3 messages? and after deletion of message a toast should appear informing 2 or 3 messages deleted.

**Steps to reproduce it**

Count the number of messages selected to delete and display it in alert dialog.

**Screenshots of the issue**

del1

del2

**Would you like to work on the issue?**

Yes i would like to work on this.

### PR DESCRIPTION
**Pull request by saketkumar95**
Fixes issue [#410](https://github.com/fossasia/susi_android/issues/410)

Changes: Now the delete dialog shows how much messages the user is deleting with a toast message of number of messages deleted.

Screenshots for the change: 

delete1

delete2

### CODE REVIEW

**Comment by mariobehling** [comment]
CirlceCI is not passing. Please check. Thank you.

File: app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java [hunk 1]
```diff
@@ -627,37 +627,63 @@ public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
...
                     AlertDialog.Builder d = new AlertDialog.Builder(context);
-                    d.setMessage("Are you sure ?").
-                            setCancelable(false).
-                            setPositiveButton("Delete", new DialogInterface.OnClickListener() {
-                                @Override
-                                public void onClick(DialogInterface dialog, int which) {
-
-                                    for (int i = getSelectedItems().size() - 1; i >= 0; i--) {
-                                        deleteMessage(getSelectedItems().get(i));
+                    if (nSelected == 1) {
```
Comment (saketkumar95) [inline app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java]: why snackbar? In most of the apps Toast is being used to display such type of informations.

**Comment by saketkumar95** [comment]
@the-dagger Please check circleci. It shows : 

remote: Invalid username or password.
fatal: Authentication failed for 'https://the-dagger:@github.com/fossasia/susi_android/'

File: app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java [hunk 2]
```diff
@@ -630,40 +630,72 @@ public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
...
+                        cancel.setTextColor(Color.BLUE);
+                        Button delete = alert.getButton(DialogInterface.BUTTON_POSITIVE);
+                        delete.setTextColor(Color.RED);
+                        return true;
+
+                    }
+                    else {
+                        AlertDialog.Builder d = new AlertDialog.Builder(context);
+                        d.setMessage("Delete "+ getSelectedItems().size() + " messages?").
+                                setCancelable(false).
```
Comment (chiragw15) [inline app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java]: @saketkumar95 I think there is no need of writing all code of alert dialog box in else statement. It can be written once and you can just write 
```
if (getSelectedItems().size() == 1){  
    d.setMessage("Delete message?")
} else { 
    d.setMessage("Delete "+ getSelectedItems().size() + " messages?") 
}
```
same while showing toast.

File: app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java [hunk 3]
```diff
@@ -630,40 +630,72 @@ public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
...
+                        Button cancel = alert.getButton(DialogInterface.BUTTON_NEGATIVE);
+                        cancel.setTextColor(Color.BLUE);
+                        Button delete = alert.getButton(DialogInterface.BUTTON_POSITIVE);
+                        delete.setTextColor(Color.RED);
+                        return true;
+
+                    }
+                    else {
+                        AlertDialog.Builder d = new AlertDialog.Builder(context);
+                        d.setMessage("Delete "+ getSelectedItems().size() + " messages?").
```
Comment (chiragw15) [inline app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java]: @saketkumar95 I think there is no need of writing all code of alert dialog box in else statement. It can be written once and you can just write 
```
if (getSelectedItems().size() == 1){  
    d.setMessage("Delete message?")
} else { 
    d.setMessage("Delete "+ getSelectedItems().size() + " messages?") 
}
```
same while showing toast.

Comment (saketkumar95) [inline app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java]: yeah i did that only in my last commit but circleci was failing and i wasn't aware why so i rewrote all the stuffs again. But Now i know why , so i will send the new PR after the circleci tests passes.

Comment (the-dagger) [inline app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java]: You can go ahead and send the PR.
Builds are failing only while pushing the generated apk onto github which seems like an issue from CircleCi's end.

**Comment by saketkumar95** [comment]
@the-dagger Now you can review the new PR.

**Comment by mayank408** [comment]
@saketkumar95 There was already snackbar why would you have implemented toast message . We are following material design guidelines.

**Comment by saketkumar95** [comment]
@mayank408 most of the apps use toast message to display any such informations. You can check in whatsapp or Google Allo. Snackbar is also not a problem but for user experience. I think toast is a much better option. :)
