### PR TITLE
fix: Checking null along with empty 

### LINKED ISSUE #1893: App crashes on scrolling down while in skills activity
**Describe the bug**

App crashes on scrolling down while in skills activity

**Expected Behaviour**
App should not crash

**Steps to reproduce it**
1. Goto skills activity
2. Scroll down
3. App crashes

**Screenshots of the issue**
whatsappvideo20190201at34

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [e.g. Moto G4 Plus] |
|Android Version| [Nougat 7.0]     |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ravi-kishan**
Fixes #1893 App crashes on scrolling down while in skills activity

Changes: 
Replaced .empty() function with null check for skillName as it was causing error on null string.

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt [hunk 1]
```diff
@@ -21,18 +22,19 @@ class SkillListAdapter(val context: Context, private val skillDetails: List<Skil
...
 
-            if (skillData.skillName.isEmpty()) {
+            if (TextUtils.isEmpty(skillData.skillName)) {
                 holder.skillPreviewTitle.text = context.getString(R.string.no_skill_name)
             } else {
                 holder.skillPreviewTitle.text = skillData.skillName
             }
 
-            if (skillData.examples.isEmpty())
+            if (skillData.examples == null || skillData.examples.isEmpty()) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt]: Is this one special?

Comment (ravi-kishan) [reply app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt]: This one is List<String> , TextUtils was not working on it.
I found this approach in SkillsListAdapter

**Comment by iamareebjamal** [comment]
add a semantic commit or PR title
