### PR TITLE
Fixed style issues (Fixed #1328)

### LINKED ISSUE #1328: Fix style issues
[Parent issue #1311]
 
**Actual Behaviour**

Currently, there are a number of style issues that appear on running lint check : 
- Replace accessor calls with property access syntax (e.g. replace setText() by text)
- Simplify boolean expressions
- Replace if statement with three or ore branches with a when statement
- Use private modifiers wherever needed
- Convert if, when and try statements to expressions by lifting a return or an assignment out 

**Expected Behaviour**

These style issues should be fixed for a more uniform code style as per the Kotlin conventions.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1328 [Parent #1311 ]

Changes: Added modifications to style :
- Replaced accessor calls with property access syntax (e.g. replace setText() by text)
- Simplified boolean expressions
- Replaced if statement with three or ore branches with a when statement
- Used private modifiers wherever needed
- Converted if, when and try statements to expressions by lifting a return or an assignment out

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arundhati24 Please resolve conflicts

**Comment by arundhati24** [comment]
@iamareebjamal Resolved the conflicts.

File: app/src/androidTest/java/org/fossasia/susi/ai/chat/ChatActivityTest.kt [hunk 1]
```diff
@@ -84,6 +84,6 @@ class ChatActivityTest {
     }
 
     companion object {
-        private val TAG = "ChatActivityTest"
+        private const val TAG = "ChatActivityTest"
```
Comment (iamareebjamal) [inline app/src/androidTest/java/org/fossasia/susi/ai/chat/ChatActivityTest.kt]: Create issue to replace log with Timber

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 2]
```diff
@@ -53,16 +53,16 @@ class ChatActivity : AppCompatActivity(), IChatView {
     val TAG: String = ChatActivity::class.java.name
 
     lateinit var chatPresenter: IChatPresenter
-    val PERM_REQ_CODE = 1
-    lateinit var recyclerAdapter: ChatFeedRecyclerAdapter
+    private val PERM_REQ_CODE = 1
+    private lateinit var recyclerAdapter: ChatFeedRecyclerAdapter
     var textToSpeech: TextToSpeech? = null
     var recordingThread: RecordingThread? = null
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: private?

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: @iamareebjamal As these members are being used only within this activity and could be made private, therefore I used the private access modifier here.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: I meant why not the variables on review line are private?

Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: @iamareebjamal Made textToSpeech private. But, recordingThread has not been made private because it is being used in STTfragment.kt .

screen shot 2018-05-31 at 10 19 33 am

**Comment by arundhati24** [comment]
@akshatnitd @batbrain7 Resolved conflicts.
