### PR TITLE
fix: Display the entire email string for the logged in user

### LINKED ISSUE #1680: Email of the logged-in user should not be anonymised in the feedback section
**Actual Behaviour**
* The email of all the users are anonymised.

**Expected Behaviour**
* Email of the logged-in user should not be anonymised

**Would you like to work on the issue?**
No, @arundhati24 Could you please fix this?

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1680

Changes: The email of all the users was anonymized in the feedback section. Now, the
email of the logged in user will not be anonymized.

Screenshots for the change: 

**BEFORE**

screenshot_2018-09-02-10-28-05-631_ai susi

screenshot_2018-09-02-10-28-11-972_ai susi

**AFTER**

screenshot_2018-09-02-10-18-59-899_ai susi

screenshot_2018-09-02-10-19-04-054_ai susi

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt [hunk 1]
```diff
@@ -40,7 +42,15 @@ class AllReviewsAdapter(val context: Context, val feedbackList: List<Feedback>?)
                 if (feedbackList[position].email != null &&
                         !TextUtils.isEmpty(feedbackList[position].email)) {
                     Utils.setAvatar(context, feedbackList.get(position).email, holder.avatar)
-                    Utils.truncateEmailAtEnd(feedbackList.get(position).email)?.let { holder.feedbackEmail?.text = it }
+                    if (PrefManager.getToken() != null) {
+                        if (!feedbackList.get(position).email.equals(PrefManager.getStringSet(Constant.SAVED_EMAIL).iterator().next().toString(), true)) {
```
Comment (codedsun) [inline app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt]: we shall used strings file here, instead of constants file.

File: app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt [hunk 2]
```diff
@@ -52,7 +54,15 @@ class FeedbackAdapter(val context: Context, val feedbackResponse: GetSkillFeedba
                         if (feedbackResponse.feedbackList[position].email != null &&
                                 !TextUtils.isEmpty(feedbackResponse.feedbackList[position].email)) {
                             Utils.setAvatar(context, feedbackResponse.feedbackList.get(position).email, holder.avatar)
-                            Utils.truncateEmailAtEnd(feedbackResponse.feedbackList.get(position).email)?.let { holder.feedbackEmail?.text = it }
+                            if (PrefManager.getToken() != null) {
+                                if (!feedbackResponse.feedbackList.get(position).email.equals(PrefManager.getStringSet(Constant.SAVED_EMAIL).iterator().next().toString(), true)) {
```
Comment (codedsun) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt]: same as above!

File: app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt (hunk 1 above)
Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt]: @codedsun This is fine because there is no duplication here. In the PR where you were asked to use stings, there we had duplicatIon i.e. same keys were being referenced from string resource files in some files while in others it was beig done from Constants file. That resulted in duplication, which is bad.
