### PR TITLE
fix: re-implemented search process to show results of search query

### LINKED ISSUE #1902: Searching is not working in SUSI.AI
**Describe the bug**

'Search' a SUSI.AI skills option is not working in application. Whenever I press a button on keypad to search any skill a toast message appears says `No skill found yet `, which may be annoying to user and on searching it is not showing any result ,i.e, search button is not working.
**Expected Behaviour**
It should search the skill for which keyword is typed in the search bar and give the relevant output.It should not show the toast message while typing as may be annoying to the user.

**Screenshots of the issue**

screenshot_20190202-143330

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by naman653**
Fixes #1902 #1827 #1800 #1782 #1353 

Changes: I've reimplemented the logic for the search process so as provide proper feedback and results for the search query.

Screenshots for the change: 
m

### CODE REVIEW

**Comment by naman653** [comment]
@iamareebjamal @batbrain7 @arundhati24 Please review and help me fix these codacy quality issues.

**Comment by naman653** [comment]
@iamareebjamal I tried solving these issues. Can you please review and help if these issues need to be solved or not.

**Comment by iamareebjamal** [comment]
@atm1504 Please review

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 1]
```diff
@@ -257,21 +235,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
-                skillMetrics.scrollToPosition(pos)
-                return true
-            }
+        var searchedSkillsList: ArrayList<SkillData> = arrayListOf()
 
-            for (item2 in item.second) {
-                if (query.toLowerCase() in item2.group.toLowerCase()) {
-                    skillMetrics.scrollToPosition(pos)
-                    return true
+        for ( skill_ in skills) {
```
Comment (atm1504) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: We don't use "skill_" this kind of variable name. It should be "skill"

File: app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+    }
+
+    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
+        return inflater.inflate(R.layout.fragment_group_wise_skill_listing, container, false)
+    }
+
+    @NonNull
+    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+        query = arguments!!.getString(SEARCH_KEY)
+        skillSet = arguments!!.getParcelableArrayList(SKILL_DATA)
```
Comment (atm1504) [inline app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt]: Don't use !! operator.

**Comment by atm1504** [comment]
@iamareebjamal I have reviewed it. Some changes needs to be done. Else everything worked fine. I have tested it in my phone also.

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal I have reviewed it with the possible errors I can find sir.

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 1 above)
Comment (naman653) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Yes, I know. I was testing something so I used that, I'll change that.

File: app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt (hunk 2 above)
Comment (naman653) [reply app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt]: Well, I was unable to do that because it creates a problem in casting. I tried to remove that but the base declarations are not coping with the change. I'll try but if you can suggest something. @iamareebjamal Please suggest any alternative approach.

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt]: You can use ?. operator and check. I hope it would work.

Comment (naman653) [reply app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt]: Of course, I'd tried that, but as I said it creates a problem in casting. Maybe @iamareebjamal can suggest a better approach

Comment (naman653) [reply app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt]: Sorry, I resolved that with using ?. operator. Thanks for your review.

**Comment by naman653** [comment]
@iamareebjamal I resolved all the possible conflicts, Please review.

**Comment by naman653** [comment]
@iamareebjamal please review and help resolve the conflicts
