### PR TITLE
fix: Remove signup if user logged in

### LINKED ISSUE #2083: Remove sign up option in skill menu if user logged in
**Describe the bug**
Instead  sign up is disabled we can just remove the option if  user is logged for a better interface.

**Expected Behaviour**
Sign up should hide if user is logged in.

**Steps to reproduce it**

Login and go for skills menu .Sign up option is present which seems disabled.

**LogCat for the issue**

**Screenshots of the issue**
Screenshot_20190326_230530

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo 1802|
|Android Version|8.1.0 |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by chanmol1999**
Fixes #2083 
Changes:skills activity

Screenshots for the change: 
Screenshot_20190411_233025
Screenshot_20190411_233008

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 1]
```diff
@@ -280,6 +280,14 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
             is SkillListingFragment -> menu?.setGroupVisible(R.id.menu_items, true)
             else -> menu?.setGroupVisible(R.id.menu_items, false)
         }
+        val signUpMenuItem = menu?.findItem(R.id.menu_signup)
+        val loginMenuItem = menu?.findItem(R.id.menu_login)
+
+        if (!settingsPresenter.getAnonymity()) {
+            loginMenuItem?.setTitle("Logout")
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Hardcoded title string.

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 2]
```diff
@@ -280,6 +280,14 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
             is SkillListingFragment -> menu?.setGroupVisible(R.id.menu_items, true)
             else -> menu?.setGroupVisible(R.id.menu_items, false)
         }
+        val signUpMenuItem = menu?.findItem(R.id.menu_signup)
+        val loginMenuItem = menu?.findItem(R.id.menu_login)
+
+        if (!settingsPresenter.getAnonymity()) {
+            loginMenuItem?.setTitle(getString(R.string.action_log_out));
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: ';' ?
