### PR TITLE
Send device_type=Android in the chat.json query

### LINKED ISSUE #1406: Send device type in chat.json API
The type of device ie, "Android" is  required to get device wise usage analytics.

**Steps to reproduce it**

NA

**LogCat for the issue**

https://api.susi.ai/susi/chat.json?q=hello&language=en&access_token=PGbzC5zYQBQUuCrYrarqIuRe4lvjfn&latitude=30.1667&longitude=77.3

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
Fixes #1406 
Send device type in chat.json API 

Changes: 
Modified getSusiMessage() and getTableSusiMessage() functions to send device_type="Android" in the query 

Screenshots for the change: 
NA

### CODE REVIEW

**Comment by batbrain7** [comment]
@iamareebjamal please merge this

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt [hunk 1]
```diff
@@ -41,6 +41,7 @@ class ChatPresenter(chatActivity: ChatActivity) : IChatPresenter, IChatModel.OnR
     private var micCheck = false
     var latitude: Double = 0.0
     var longitude: Double = 0.0
+    var deviceType: String = "Android"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: Why not private val?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: Also, type inference will get the type automatically, no need to specifically name it

Comment (AnupKumarPanwar) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: I've followed the existing code pattern, as used by the latitude and longitude since they relate to the same thing.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt]: No problem, we should leave the code better than we found it, make it private val
