### PR TITLE
fix: move lambda argument out of paranthesis

### LINKED ISSUE #1708: Lambda argument should be moved out of parentheses
**Actual Behaviour**
Inside signup activity lambda expression inside parentheses which can be moved outside of them.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Fixes #1708

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt [hunk 1]
```diff
@@ -96,12 +96,12 @@ class LoginPresenter(loginActivity: LoginActivity) : ILoginPresenter, ILoginMode
             }
         } else {
             utilModel.setServer(true)
-        }
+        }l
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt]: what is this ?

**Comment by GOVINDDIXIT** [comment]
@batbrain7  Is Spotless check properly configured ?. when I tries to fix circleCI build using gradlew spotlessApply I am getting
> * What went wrong:
> Task 'spotlessApply' not found in root project 'susi_android'.

Pls guide

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal pls review
