### PR TITLE
fix: Remove quotes from environmental variable

### LINKED ISSUE #1455: Use the environment variables correctly in the app
**Actual Behaviour**

Currently the environment variables are not set in the app correctly, the youtube api key is actually stored in string format.

**Expected Behaviour**

Handle the environment variables in such a manner that they are not stored in the string format.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #1455

### CODE REVIEW

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 1]
```diff
@@ -27,22 +27,29 @@ class YouTubeActivity : YouTubeBaseActivity(), YouTubePlayer.OnInitializedListen
...
+    var apikey = ""
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         setContentView(R.layout.youtube_player)
 
-        if (BuildConfig.YOUTUBE_API_KEY.equals("YOUR_API_KEY")) {
+
+        val ai = this.packageManager.getApplicationInfo(this.getPackageName(), PackageManager.GET_META_DATA)
+        val bundle = ai.metaData
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Don't create variables which aren't used

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 2]
```diff
@@ -27,22 +27,29 @@ class YouTubeActivity : YouTubeBaseActivity(), YouTubePlayer.OnInitializedListen
...
+        apikey = bundle.getString("com.google.android.youtube.API_KEY")
+        Toast.makeText(applicationContext, "API KEY." + apikey, Toast.LENGTH_LONG).show()
```
[the remark this answers is not in the document]
Comment (batbrain7) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Sorry @iamareebjamal forgot to remove it.

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt (hunk 1 above)
Comment (batbrain7) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: @iamareebjamal bundle is used , should I eliminate it ?

Comment (batbrain7) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Now I have eliminated it.

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 3]
```diff
@@ -27,22 +27,27 @@ class YouTubeActivity : YouTubeBaseActivity(), YouTubePlayer.OnInitializedListen
...
     lateinit var playerView: YouTubePlayerView
+    var apikey = ""
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         setContentView(R.layout.youtube_player)
 
-        if (BuildConfig.YOUTUBE_API_KEY.equals("YOUR_API_KEY")) {
+
+        val ai = this.packageManager.getApplicationInfo(this.getPackageName(), PackageManager.GET_META_DATA)
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Remove this

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 4]
```diff
@@ -27,22 +27,27 @@ class YouTubeActivity : YouTubeBaseActivity(), YouTubePlayer.OnInitializedListen
     lateinit var playbackEventListener: MyPlaybackEventListener
     private var youtubeId: String = ""
     lateinit var playerView: YouTubePlayerView
+    var apikey = ""
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: In Java and Kotlin, you make properties private unless needed otherwise

Make this private lateinit var

**Comment by batbrain7** [comment]
@iamareebjamal please review

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 5]
```diff
@@ -23,19 +23,18 @@ import timber.log.Timber
...
     private val RECOVERY_REQUEST = 1;
-    lateinit var playerStateChangeListener: MyPlayerStateChangeListener
-    lateinit var playbackEventListener: MyPlaybackEventListener
+    private lateinit var playerStateChangeListener: MyPlayerStateChangeListener
+    private lateinit var playbackEventListener: MyPlaybackEventListener
     private var youtubeId: String = ""
-    lateinit var playerView: YouTubePlayerView
-    var apikey = ""
+    private lateinit var playerView: YouTubePlayerView
+    private var apikey = ""
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: lateinit var

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 6]
```diff
@@ -23,19 +23,18 @@ import timber.log.Timber
...
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         setContentView(R.layout.youtube_player)
 
-
-        val ai = this.packageManager.getApplicationInfo(this.getPackageName(), PackageManager.GET_META_DATA)
-        apikey = ai.metaData.getString("com.google.android.youtube.API_KEY")
+        apikey = this.packageManager.getApplicationInfo(this.getPackageName(), PackageManager.GET_META_DATA)
+                .metaData.getString("com.google.android.youtube.API_KEY")
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Extract this in constant

Comment (batbrain7) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: should it be lateinit var or constant ?

File: app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt [hunk 7]
```diff
@@ -33,8 +33,9 @@ class YouTubeActivity : YouTubeBaseActivity(), YouTubePlayer.OnInitializedListen
         super.onCreate(savedInstanceState)
         setContentView(R.layout.youtube_player)
 
+        val YOUTUBE_KEY = "com.google.android.youtube.API_KEY"
```
Comment (iamareebjamal) [inline app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: Make this a private const field

Comment (batbrain7) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: @iamareebjamal for this should I make a companion object or top level field?

Comment (iamareebjamal) [reply app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt]: No, just a field

**Comment by iamareebjamal** [comment]
Circle CI is not opening for me, can't change environment variable now

**Comment by batbrain7** [comment]
@iamareebjamal right now it is not opening or we cannot do it at all?
