### PR TITLE
fix: Completed Unit test of SignUpPresenter

### LINKED ISSUE #804: Write good Unit Tests to Test the working of the app
Write good quality unit tests to test the working of each component of the app. After Shifting to MVP, the testing will be a lot easier. So, write tests for everything. Make sub issues for tests related to particular issues like Login tests etc.

### PR DESCRIPTION
**Pull request by pallav12**
Fixes #804 
Changes: Completed unit tests for SignUpPresenter (**tests for minor functions like cancelSignUp(), cancelSignup() is not added because these functions do not contains any logics**)

Screenshots for the change: 
Screenshot (11)

### CODE REVIEW

File: app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt [hunk 1]
```diff
@@ -73,4 +101,80 @@ class SignUpPresenterTest {
         verify(signUpView).showProgress(true)
         verify(iSignUpModel).signUp("email@gmail.com", "P@ssword12", signUpPresenter)
     }
+
+    @Test
+    fun shouldShowErrorOnFailure() {
+        signUpPresenter.onError(Throwable())
```
Comment (pallav12) [inline app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt:107]: Ideally this should be like 
~~~
when(iSignUpModel.signUp(anyString(),anyString(),any())).then{signUpPresenter.onError(any())}
signUpPresenter.signUp("email","password",signUpPresenter)
~~~
but this doesn't works... that's why I have to call onError directly. Any suggestions??

File: app/src/main/java/org/fossasia/susi/ai/signup/SignUpPresenter.kt [hunk 2]
```diff
@@ -26,11 +26,10 @@ import retrofit2.Response
  * Created by mayanktripathi on 05/07/17.
  */
 
-class SignUpPresenter(private val signUpModel: SignUpModel, private val utilModel: UtilModel, private val databaseRepository: IDatabaseRepository, private val signUpView: ISignUpView) : ISignUpPresenter, ISignUpModel.OnSignUpFinishedListener, IForgotPasswordModel.OnFinishListener {
+class SignUpPresenter(var forgotPasswordModel: ForgotPasswordModel, private val signUpModel: SignUpModel, private val utilModel: UtilModel, private val databaseRepository: IDatabaseRepository, private val signUpView: ISignUpView) : ISignUpPresenter, ISignUpModel.OnSignUpFinishedListener, IForgotPasswordModel.OnFinishListener {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/signup/SignUpPresenter.kt]: private val

File: app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt [hunk 3]
```diff
@@ -1,17 +1,36 @@
...
+    private val NO_INTERNET_AVAILABLE = "Internet Connection Not Available."
+    private val UNKNOWN_HOST_EXPRESSINON = "Unknown Host Exception"
+
+    private var responseSuccess: retrofit2.Response<SignUpResponse> = retrofit2.Response.success(SignUpResponse("Message", null))
+    private var responseCode422: retrofit2.Response<SignUpResponse> = retrofit2.Response.error(422, ResponseBody.create(null, "content"))
+    private var responseCodeUnknown: retrofit2.Response<SignUpResponse> = retrofit2.Response.error(500, ResponseBody.create(null, "content"))
+
+    private var forgotResponseSuccess: retrofit2.Response<ForgotPasswordResponse> = retrofit2.Response.success(ForgotPasswordResponse("Message"))
+    private var forgotResponse422: retrofit2.Response<ForgotPasswordResponse> = retrofit2.Response.error(422, ResponseBody.create(null, "content"))
+    private var forgotResponseUnknown: retrofit2.Response<ForgotPasswordResponse> = retrofit2.Response.error(500, ResponseBody.create(null, "content"))
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt]: val

Comment (pallav12) [reply app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt]: Done

File: app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt (hunk 1 above)
Comment (pallav12) [reply app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt:107]: @iamareebjamal please answer... I have to use same pattern in future unit tests also.
open-event-organizer uses observables, so it's somewhat easier to test. I think directly calling onError instead of signUp doesn't makes much difference.

Comment (pallav12) [reply app/src/test/java/org/fossasia/susi/ai/signup/SignUpPresenterTest.kt:107]: also, should I also include tests for minor functions as
~~~
signUpPresenter.cancelSignUP()
verify(signUpModel).cancelSignup()
~~~

**Review by iamareebjamal — APPROVED** [review]
