### PR TITLE
fix: Added unit test for datahelper class

### LINKED ISSUE #2100: Unit tests for feedback activity
**Describe the bug**
There is no unit tests written for feedback activity

**Expected Behaviour**
There has to be unit tests on feedback activity as well using Espresso for faster results

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by pallav12**
Fixes #2100 

Changes: Made feedback activity testable and added unit test, since only testable unit in Feedback activity is format date. So migrated getDate() function to DateTimeHelper and added unit test for all other functions of DateTimeHelper

Screenshots for the change: 
Screenshot (8)

### CODE REVIEW

File: app/src/test/java/org/fossasia/susi/ai/helper/DateTimeHelperTest.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+class DateTimeHelperTest {
+    @Test
+    fun getDateTest() {
+        Assert.assertEquals(" Jan 30, 2020", DateTimeHelper.getDate("2020-01-30T12:18:37.262Z"))
+    }
+
+    @Test
+    fun formatDateTest() {
+        val countries = arrayOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Aug", "Nov", "Dec")
+        Assert.assertEquals("30 Jan, 2020", DateTimeHelper.formatDate("2020-01-30T12:18:37.262Z", countries))
```
Comment (iamareebjamal) [inline app/src/test/java/org/fossasia/susi/ai/helper/DateTimeHelperTest.kt]: Add  case for null timestamp as well

Comment (pallav12) [reply app/src/test/java/org/fossasia/susi/ai/helper/DateTimeHelperTest.kt]: @iamareebjamal added null checks as well as tests for null and empty values. One question though, I tried adding test for one remaining function ie getTime() but every time CI build is failing. That's because i have to hardcode expectation for input, but expectations would be different depending upon different timezone(github vs my), so according to me it's not possible... or is it??

Comment (iamareebjamal) [reply app/src/test/java/org/fossasia/susi/ai/helper/DateTimeHelperTest.kt]: See tests for  open-event-organizer app

Comment (pallav12) [reply app/src/test/java/org/fossasia/susi/ai/helper/DateTimeHelperTest.kt]: Thanks... that worked, implemented tests for different timezones

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt [hunk 2]
```diff
@@ -71,7 +71,11 @@ object DateTimeHelper {
         val sdf = SimpleDateFormat(" MMM dd, yyyy")
         val tz = TimeZone.getDefault()
         sdf.timeZone = tz
-        return sdf.format(formatDate(date))
+        if (formatDate(date) == null || sdf.format(formatDate(date)) == null) {
+            return ""
+        } else {
+            return sdf.format(formatDate(date))
+        }
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: If this is needed, then the argument should be made non nullable

Comment (pallav12) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Made date non nullable so this argument isn't needed any more, returning today date when cannot parse ie when null. please recheck...

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Then remove this if else

Comment (pallav12) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: removed this, and updated DateTimeHelperTest accordingly

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt [hunk 3]
```diff
@@ -85,6 +90,25 @@ object DateTimeHelper {
         val sdf = SimpleDateFormat("hh:mm aaa")
         val tz = TimeZone.getDefault()
         sdf.timeZone = tz
-        return sdf.format(formatDate(date))
+        return if (date.isEmpty()) {
+            ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Remove this

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt [hunk 4]
```diff
@@ -85,6 +90,25 @@ object DateTimeHelper {
...
+            var date: String? = ""
+            timestamp.trim()
+            val month = timestamp.substring(5, 7).toInt()
+            date = timestamp.substring(8, 10) + " " +
+                    months[month - 1].toString() +
+                    ", " + timestamp.substring(0, 4)
+
+            date
+        } else {
+            ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Remove this

Comment (pallav12) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: What exactly?? timestamp!=null can be removed by making timestamp non nullable, if else condition can't be removed because if not checked it'll expose indexOutOfBound exceptions in months and string length(So if this happens just return empty string ie don't print anything in date).

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Throw error instead

Comment (pallav12) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Thrown error and added corresponding tests, There wont be these redundancies from next time.
please notice updated screenshot also.

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: This is left

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt [hunk 5]
```diff
@@ -85,6 +90,25 @@ object DateTimeHelper {
...
+            var date: String? = ""
+            timestamp.trim()
+            val month = timestamp.substring(5, 7).toInt()
+            date = timestamp.substring(8, 10) + " " +
+                    months[month - 1].toString() +
+                    ", " + timestamp.substring(0, 4)
+
+            date
+        } else {
+            throw IllegalArgumentException()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]: Pass proper message in the exception

File: app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt [hunk 6]
```diff
@@ -85,6 +90,25 @@ object DateTimeHelper {
...
         sdf.timeZone = tz
-        return sdf.format(formatDate(date))
+        return if (date.isEmpty()) {
+            throw IllegalArgumentException()
+        } else {
+            sdf.format(formatDate(date))
+        }
+    }
+
+    fun formatDate(timestamp: String?, months: Array<String>): String? {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt]:
```suggestion
    fun formatDate(timestamp: String, months: Array<String>): String {
```

**Comment by pallav12** [comment]
Thanks @iamareebjamal  for having patience... I'll try to avoid any redundancies from now.

**Review by iamareebjamal — APPROVED** [review]
