### PR TITLE
fix: Made search, susi icon invisible in stt fragment

### LINKED ISSUE #2177: chat search icon appears in Stt fragment
**Describe the bug**
The chat search icon shows up in stt fragment as well. It is only required in chatActivity and not needed in stt fragment.
We need to remove it

Screenshots:
Screenshot_20190417-063220_SUSIAI

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2177 

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change: 
ezgif com-video-to-gif

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 1]
```diff
@@ -326,6 +328,8 @@ class ChatActivity : AppCompatActivity(), IChatView {
             chatPresenter.stopHotwordDetection()
         }
         hideSoftKeyboard(this, window.decorView)
+        searchChat.visibility = View.INVISIBLE
+        fabsetting.visibility = View.INVISIBLE
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: Why not `View.GONE`, so it will not accessible.

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 2]
```diff
@@ -334,6 +338,8 @@ class ChatActivity : AppCompatActivity(), IChatView {
 
     //Replies user with Speech
     override fun voiceReply(reply: String, language: String) {
+        searchChat.visibility = View.VISIBLE
+        fabsetting.visibility = View.VISIBLE
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: And what about it?

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: > And what about it?

When we open up sttfragment, and give some voice commands, the chat activity is not again restarted. It simply calls the function voiceReply. So, it was necessary to make the visibility here
