### PR TITLE
fix: No inverted commas shown without example

### LINKED ISSUE #1907: Inverted commas shown without example text
**Describe the bug**
Inverted commas are shown even if there are no example strings.

**Expected Behaviour**
Inverted commas should be hidden in such a case to match the style of website version

**Steps to reproduce it**
1.Open Skills Activity
2.See EnglishAIMLL

**Screenshots of the issue**
App
whatsapp image 2019-02-05 at 12 24 25 pm
Website
screenshot_2019-02-05 susi ai - browse skills 1

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [ Moto G4 Plus] |
|Android Version| [Nougat 7.0]     |

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by ravi-kishan**
Fixes #1907 Inverted commas shown without example text

Changes: 
Changed code to not add inverted commas if examples list is empty.

Screenshots for the change: 
whatsapp image 2019-02-07 at 2 50 29 pm

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt [hunk 1]
```diff
@@ -41,7 +41,7 @@ class SkillsListAdapter(val context: Context, private val skillDetails: GroupWis
             }
 
             if (skillData.examples == null || skillData.examples.isEmpty())
-                holder.skillExample?.text = StringBuilder("\"").append("\"")
+                holder.skillExample?.text = StringBuilder("")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt]: You are not building a string, so there is no need of string builder

File: app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt [hunk 2]
```diff
@@ -29,7 +29,7 @@ class SkillListAdapter(val context: Context, private val skillDetails: List<Skil
             }
 
             if (skillData.examples == null || skillData.examples.isEmpty()) {
-                holder.skillPreviewExample.text = StringBuilder("\"").append("\"")
+                holder.skillPreviewExample.text = StringBuilder("")
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt]: Same
