### PR TITLE
"double circularProgressBarFix"

### LINKED ISSUE #1227: Two Circular progress Bar onSwipetorefresh() in skill activity
#**Actual Behaviour**
In SUSI.AI Skills activity when we swipe to refresh the skills data along with one default circular progress bar,  Another progress bar which we defined in layout also starts. 

**Expected Behaviour**
if we hit Swipe to refresh only default circular progress 
bar should be shown. when the activity is loaded then only progress bar from activity layout should be shown

**Steps to reproduce it**
when we are loading groups in "fetchGroups()" in SKillListingPresenter() we should check for we are loading on activity creation or for onRefresh

**Screenshots of the issue**
 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by storytellerr**
Fixes #1227 

Changes: added a check before fetchGroups() in skillListingPresenter that we are loading skill data on activity creation or for Refresh

Screenshots for the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt [hunk 1]
```diff
@@ -28,7 +28,7 @@ class SkillListingPresenter: ISkillListingPresenter,
         this.skillListingView = skillListingView
     }
 
-    override fun getGroups() {
+    override fun getGroups(swipeToRefreshActive:Boolean) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt]: Space after :

File: app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingPresenter.kt [hunk 2]
```diff
@@ -6,6 +6,6 @@ package org.fossasia.susi.ai.skills.skilllisting.contract
  */
 interface ISkillListingPresenter {
     fun onAttach(skillListingView: ISkillListingView)
-    fun getGroups()
+    fun getGroups(swipeToRefreshActive:Boolean)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingPresenter.kt]: Space after :
