### PR TITLE
Send country code and name in chat.json API (Fixed #1394)

### LINKED ISSUE #1394: Send country name and country code in chat.json API
**Actual Behaviour**

Only latitude and longitude are send as API parameters.

**Expected Behaviour**

Country code and country name are also required to get country wise usage analytics.

**Steps to reproduce it**

Check `\susi_android\app\src\main\java\org\fossasia\susi\ai\chat\ChatPresenter.kt`

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

I think @batbrain7 and @arundhati24  can solve it.

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1394 

Changes: Now country code and name is also sent as a query in chat.json API.

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt [hunk 1]
```diff
@@ -72,9 +74,11 @@ class ChatModel : IChatModel {
     }
 
     override fun getTableSusiMessage(timezoneOffset: Int, longitude: Double, latitude: Double, source: String,
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt]: Too many params, convert to object
