### PR TITLE
fix: fixes crash

### LINKED ISSUE #1992: App crashes due IllegalStateException
**Describe the bug**

The swipe_refresh_layout becomes null when the fragment is changed from SkillListing and crashes

**Expected Behaviour**

The app shouldn't crash in that case

**Steps to reproduce it**

1. Open the application
2. Click the Susi logo
3. Immediately go into settings page or about us page
4. wait for some time
5. app will crash

**LogCat for the issue**

2019-03-03 12:04:31.040 3403-3403/ai.susi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.susi, PID: 3403
    java.lang.IllegalStateException: swipe_refresh_layout must not be null
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingFragment.updateSkillsAdapter(SkillListingFragment.kt:99)
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingPresenter.onSkillFetchSuccess(SkillListingPresenter.kt:86)
        at org.fossasia.susi.ai.data.SkillListingModel$fetchSkills$1.onResponse(SkillListingModel.kt:48)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by immadisairaj**
Fixes #1992

Changes:
Whenever the cancel is called the fetching process is continuing. So, if we put it in the while loop till all the calls are cancelled then it'll be working fine.

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt [hunk 1]
```diff
@@ -73,9 +73,12 @@ class SkillListingModel : ISkillListingModel {
...
         try {
-            authResponseCallGroups.cancel()
-            authResponseCallSkills.cancel()
-            authResponseCallMetrics.cancel()
+            while (!authResponseCallGroups.isCanceled)
+                authResponseCallGroups.cancel()
+            while (!authResponseCallSkills.isCanceled)
+                authResponseCallSkills.cancel()
+            while (!authResponseCallMetrics.isCanceled)
+                authResponseCallMetrics.cancel()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: This is strangest use of while loop I have ever seen!

Comment (immadisairaj) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: Can you please suggest what can be done instead

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: There is no need of while loop. Simply  solve the memory leak using common practices

Comment (immadisairaj) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: Can I use Handler().postDelayed

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: No

Comment (immadisairaj) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: Can I use boolean to check if the fetch is called or not

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt]: You simply need to return from the callbacks if the presenter is destroyed

**Comment by immadisairaj** [comment]
@iamareebjamal 
I checked if the presenter is destroyed then it calls cancelFetch(). I just returned from not fetching before it starts to fetch. But if cancelFetch() is called after the fetching starts then I cancel all the calls

**Comment by iamareebjamal** [comment]
I'm sorry but you're not able to understand what I'm trying to say. Analyse the situation in more detail and tell me why null pointer exception is happening and why not just returning before the call from where NPE is happening won't solve the problem

**Comment by immadisairaj** [comment]
@iamareebjamal 
This is what I understood. In the SkillListingPresenter we are changing the skillListingView to null. All the fragment views will become null. When we are fetching skills we are also updating the views in the fragment where there are no views. So, Checked whether the view is null initially and returned without fetching anything.
Is this what you were saying or did I again misunderstood?
