### PR TITLE
fix: remove hungarian notation

### LINKED ISSUE #1689: Remove hungarian notation from project
**Actual Behaviour**

There are Hungarian notation used in the project for naming the variables

**Expected Behaviour**

They should not be used.

**Would you like to work on the issue?**

You can take it if you can

### PR DESCRIPTION
**Pull request by immadisairaj**
Fixes #1689, #1688

Changes: Removed Hungarian notations in all the files, Replaced single variable names with appropriate names, changed shortcut variable names with appropriate names

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt [hunk 1]
```diff
@@ -287,11 +287,11 @@ class ChatActivity : AppCompatActivity(), IChatView {
                     }
                 })
 
-                val ttsParams = HashMap<String, String>()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt]: Revert

**Comment by immadisairaj** [comment]
@iamareebjamal made changes as requested. Can you please review this.
