### PR TITLE
fix: Fixed malfunction of settings fragment

### LINKED ISSUE #2055: Settings page malfunctions on moving back from about us
**Describe the bug**
Settings page shows malfunctioning on moving back from about us to settings .Many features including login/logout do not work properly.

**Expected Behaviour**

Settings page should work  as normal as it was working previously.

**Steps to reproduce it**
change in chat setttings fragment

**LogCat for the issue**

**Screenshots of the issue**
Screenrecording_20190322_030236 (1)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo 1802|
|Android Version|8.1.0    |

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2055 

Changes: [Add here what changes were made in this issue and if possible provide links.]
Fixed it by checking whether the user is logged in or not. Initially, it used only anonymity as a parameter to check

Screenshots for the change: 
settings

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt [hunk 1]
```diff
@@ -216,6 +219,9 @@ class ChatSettingsFragment : PreferenceFragmentCompat(), ISettingsView {
 
         displayEmail.setOnPreferenceClickListener {
             settingsPresenter.loginLogout()
+            val intent = Intent(context, LoginActivity::class.java)
+            intent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_NEW_TASK
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: Not a good idea for `FLAG_ACTIVITY_CLEAR_TOP`. What if we go back after intent, it should redirect to chat screen. Right?

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: It will redirect to the settings fragment only. And I think it should redirect there only, as we have opened the login screen from there itself

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: > It will redirect to the settings fragment only.

Your intent is redirecting to Login activity and clear all activities in the back stack. Right?

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: Yah. Why keep the back stack filled once we are moving to the login page? Because after login the user will be redirected to the chat page. So, it's better to free up the stack

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: IMO, not better user experience. Back button should redirect to chat screen instead of closing the application.

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: @liveHarshit u want to say that if we press the back button at the login screen, it should redirect to the chat screen. R8?

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt]: Yes.

File: app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt [hunk 2]
```diff
@@ -228,4 +228,9 @@ class LoginActivity : AppCompatActivity(), ILoginView {
             loginPresenter.requestPassword(email, url, isPersonalServerChecked)
         }
     }
+
+    override fun onBackPressed() {
+        super.onBackPressed()
+        startActivity(Intent(this, ChatActivity::class.java))
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt]: Okay, add a flag to clear back stack here.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by liveHarshit** [comment]
> You can remove duplication by creating a common method in `ChatSettingsFragment`

@atm1504 Please update pending PRs and resolve conflicts. And request a review from mentors.

**Comment by atm1504** [comment]
> > You can remove duplication by creating a common method in `ChatSettingsFragment`
> 
> @atm1504 Please update pending PRs and resolve conflicts. And request a review from mentors.

Yah sure

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 please review it.

File: app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt [hunk 3]
```diff
@@ -228,4 +228,11 @@ class LoginActivity : AppCompatActivity(), ILoginView {
             loginPresenter.requestPassword(email, url, isPersonalServerChecked)
         }
     }
+
+    override fun onBackPressed() {
+        super.onBackPressed()
+        val intent = Intent(this, ChatActivity::class.java)
+        intent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_NEW_TASK
+        startActivity(intent)
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt]: Wrong

**Comment by atm1504** [comment]
@iamareebjamal please review now. I have corrected it.

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 please review it.

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 please review it.

File: app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt [hunk 4]
```diff
@@ -230,6 +230,7 @@ class LoginActivity : AppCompatActivity(), ILoginView {
     }
 
     override fun onBackPressed() {
+        super.onBackPressed()
         loginPresenter.skipLogin()
         super.onBackPressed()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt]: Why twice?

Comment (atm1504) [reply app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt]: THis happened by mistake while resolving the merge conflict. Have removed it in the update.
