### PR TITLE
fix: make examples sections invisible when example list is empty

### LINKED ISSUE #1564: Examples section visible even when the examples list is empty
**Actual Behaviour**

Currently, the example section is visible in the skills details screen even when the examples list received from the server is empty.

**Expected Behaviour**

If the examples list is empty, the examples section should be hidden.

**Screenshot of the issue**

emptyexamples

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1564 : Made examples sections invisible when example list is empty

Changes: Set the visibility to gone

Edit:

Screenshots:

screenshot-1534774596095

@arundhati24 @batbrain7 Check this!

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt [hunk 1]
```diff
@@ -188,11 +188,14 @@ class SkillDetailsFragment : Fragment(), ISkillDetailsView {
     }
 
     private fun setExamples() {
-        if (skillData.examples != null) {
+        if (skillData.examples != null && skillData.examples.isNotEmpty()) {
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt]: ```if (!skillData.examples.isNullOrEmpty())```

**Comment by arundhati24** [comment]
@codedsun  Could you please add a screenshot of the EnglishAIML skill, which has no examples?

File: app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt (hunk 1 above)
Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt]: @arundhati24 is this function available for a list type? it's for a text type IMO.

**Comment by iamareebjamal** [comment]
Not following:

- Tag is always lowercase
- There is a space after tag color
- Commit message is always imperative (Make, not Made). Read the guide mentioned earlier again

**Comment by codedsun** [comment]
@iamareebjamal I am really very very sorry this time, I am always trying to make it as close as possible I read all the guidelines, but I am still not able to follow.


This time, you have guided me and I have kept the screenshot of it, 👍 Thanks for the comment will always watch this ss before any commit.
