### PR TITLE
fix: replaced calls to github by susi server

### LINKED ISSUE #1574: Make call to SUSI server instead of getting data from github
**Actual Behaviour**

Currently there are 3 API calls to github links to get the image of the skills.

**Expected Behaviour**

All the API calls should be made to the server.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #1574 
Changes: All calls are now made to the susi server

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt [hunk 1]
```diff
@@ -112,8 +111,10 @@ class SkillDetailsFragment : Fragment(), ISkillDetailsView {
     private fun setImage() {
         skillDetailImage.setImageResource(R.drawable.ic_susi)
         if (skillData.image != null && !skillData.image.isEmpty()) {
-            Picasso.with(activity?.applicationContext).load(StringBuilder(imageLink)
-                    .append(skillGroup).append("/en/").append(skillData.image).toString())
+            Picasso.with(activity?.applicationContext)
+                    .load(StringBuilder(imageLink)
+                            .append("model=" + skillData.model + "&language=" + skillData.language + "&group=" + skillData.group.replace(" ", "%20"))
+                            .append("&image=").append(skillData.image).toString())
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt]: Make it a function and reuse

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt]: Yes, so make the function in a Utils file. Separate classes are not an excuse for duplication

File: app/src/main/java/org/fossasia/susi/ai/Utils/UIutils.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
+package org.fossasia.susi.ai.Utils
+
+import android.widget.ImageView
+import com.squareup.picasso.Picasso
+import org.fossasia.susi.ai.R
+import org.fossasia.susi.ai.rest.clients.BaseUrl
+import org.fossasia.susi.ai.rest.responses.susi.SkillData
+
+class UIutils {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/Utils/UIutils.kt]: There must be a utils file already, use that

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/Utils/UIutils.kt]: There is no utils file there is once mediaUtilfile for microphone and audio handling and networkUtil for network checking

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/Utils/UIutils.kt]: Why is the package name in capitals?

Also, change the class to object and name to `Utils` 

Besides `UIutils` is not valid camel case

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/Utils/UIutils.kt]: There's already a helper package, add the class there

File: app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt [hunk 3]
```diff
@@ -1,12 +1,12 @@
...
+package org.fossasia.susi.ai.helper
 
 import android.widget.ImageView
 import com.squareup.picasso.Picasso
 import org.fossasia.susi.ai.R
 import org.fossasia.susi.ai.rest.clients.BaseUrl
 import org.fossasia.susi.ai.rest.responses.susi.SkillData
 
-class UIutils {
+class ImageUtils {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt]: Make this object

File: app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt [hunk 4]
```diff
@@ -0,0 +1,23 @@
+package org.fossasia.susi.ai.helper
+
+import android.widget.ImageView
+import com.squareup.picasso.Picasso
+import org.fossasia.susi.ai.R
+import org.fossasia.susi.ai.rest.clients.BaseUrl
+import org.fossasia.susi.ai.rest.responses.susi.SkillData
+
+class ImageUtils {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt]: object

File: app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+
+    private val imageLink = BaseUrl.SUSI_DEFAULT_BASE_URL + "/cms/getImage.png?"
+
+    fun setSkillsImage(skillData: SkillData, imageView: ImageView) {
+        Picasso.with(imageView.context)
+                .load(StringBuilder(imageLink)
+                        .append("model=" + skillData.model + "&language=" + skillData.language + "&group=" + skillData.group.replace(" ", "%20"))
+                        .append("&image=").append(skillData.image).toString())
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/ImageUtils.kt]: Add a method which takes skillData and returns a string

Think about testability

**Comment by iamareebjamal** [comment]
2 days ago:

> Also, change the class to object and name to Utils

1 day ago:

> Make this object

Today:

> object

Please don't flag for review unless the required change list is not fulfilled

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt [hunk 6]
```diff
@@ -6,18 +6,22 @@ import org.fossasia.susi.ai.R
...
                 .fit()
                 .centerCrop()
                 .into(imageView)
     }
-}
\ No newline at end of file
+
+    fun getLink(skillData: SkillData): String {
+        return StringBuilder(imageLink)
+                .append("model=" + skillData.model + "&language=" + skillData.language + "&group=" + skillData.group.replace(" ", "%20"))
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: What's the use of StringBuilder if you are concatenating strings in the end?

Use kotlin string interpolation instead

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt [hunk 7]
```diff
@@ -6,18 +6,22 @@ import org.fossasia.susi.ai.R
...
+                .load(getLink(skillData))
                 .error(R.drawable.ic_susi)
                 .fit()
                 .centerCrop()
                 .into(imageView)
     }
-}
\ No newline at end of file
+
+    fun getLink(skillData: SkillData): String {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: `getImageLink`

File: app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt [hunk 8]
```diff
@@ -19,7 +19,7 @@ class SkillListAdapter(val context: Context, private val skillDetails: List<Skil
         SkillViewHolder.ClickListener {
 
     private val clickListener: SkillViewHolder.ClickListener = this
-    private lateinit var uiUtils: ImageUtils
+    private lateinit var uiUtils: Utils
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt]: No need for this, Utils is a singleton

Read about kotlin objects

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt [hunk 9]
```diff
@@ -0,0 +1,23 @@
...
+        Picasso.with(imageView.context)
+                .load(getImageLink(skillData))
+                .error(R.drawable.ic_susi)
+                .fit()
+                .centerCrop()
+                .into(imageView)
+    }
+
+    fun getImageLink(skillData: SkillData): String {
+        return "BaseUrl.SUSI_DEFAULT_BASE_URL + \"/cms/getImage.png?\"" + "model=" + "$skillData.model" + "&language=" + "$skillData.language" + "&group=" +
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: I don't know what you changed but this is still neither StringBuilder, nor kotlin string interpolation

You add changes and reviews get dismissed and changes are still not addressed

Please comment here what you are going to change so that we are on the same page

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: @iamareebjamal i did not change anything, only the branch was made even and I don't know how the changes got outdated, it is strange also I did not request review recently as I did not make any change here, 

further instead of concatenating I will simply make a string and append the skillData.params as ${skillData.params} in the string , but what I don't know is how to handle the part where the space is to be replaced by "%20"

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: First of all, you have to remove all the `+` signs

This is string concatenation, you should not concatenate strings, read about this

And kotlin string interpolation is not about converting

`"OK" + skillData.model + "fine:" + skillData.done`

into this:

`"OK" + "$skillData.model" + "fine:" + "$skillData.done"`

How is this better?

This is still string concatenation and you are now creating even more strings by converting `skillData.param` to a String

This should be like this

`"OK${skillData.model}fine:${skillData.done}"`

It seems you didn't read about it. Also about "converting spaces to %20", it's called encoding URLs, read about it and follow up here before sending a commit

**Comment by iamareebjamal** [comment]
@batbrain7 Please finalize this ASAP, this and #1614 are blockers for #1557

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt (hunk 9 above)
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: @iamareebjamal I have made this  : 
return "{$imageLink}model={$skillData.model}&language={$skillData.language}&group=" +
                StringBuffer(skillData.group.replace(" ", "%20")).toString() + "&image={$skillData.image}"

Now I don't understand how to replace StringBuilder

**Comment by batbrain7** [comment]
@iamareebjamal how to add interpolation in url encoding ?

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt [hunk 10]
```diff
@@ -16,8 +17,8 @@ object Utils {
     }
 
     fun getImageLink(skillData: SkillData): String {
-        return "BaseUrl.SUSI_DEFAULT_BASE_URL + \"/cms/getImage.png?\"" + "model=" + "$skillData.model" + "&language=" + "$skillData.language" + "&group=" +
-                StringBuffer(skillData.group.replace(" ", "%20")).toString() + "&image=" + "$skillData.image"
+        return "${BaseUrl.SUSI_DEFAULT_BASE_URL}/cms/getImage.png?model=${skillData.model}&language=${skillData.language}&group=" +
+                StringBuffer(skillData.group.replace(" ", "%20")).toString() + "&image=${skillData.image}"
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: Use URL encoding

File: app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt [hunk 11]
```diff
@@ -17,8 +18,8 @@ object Utils {
     }
 
     fun getImageLink(skillData: SkillData): String {
-        return "${BaseUrl.SUSI_DEFAULT_BASE_URL}/cms/getImage.png?model=${skillData.model}&language=${skillData.language}&group=" +
-                StringBuffer(skillData.group.replace(" ", "%20")).toString() + "&image=${skillData.image}"
+        val uri = URI("${BaseUrl.SUSI_DEFAULT_BASE_URL}/cms/getImage.png?model=${skillData.model}&language=${skillData.language}&group=${skillData.group}&image=${skillData.image}")
```
[the remark this answers is not in the document]
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: tests as in unit testing tests ?

[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: Yes

[the remark this answers is not in the document]
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: @iamareebjamal can I add tests after the release of this version ?

[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt]: OK, but without tests, I don't know if the solution is correct
