### PR TITLE
Fixes #446 Now photos can be selected using Google photos

### LINKED ISSUE #446: Wallpaper Not changing
**Actual Behavior**

Wallpaper isn't changing.
The image to be applied changes its aspect ratio and saves as a new version of the actual image.

**Expected Behavior**

Wallpaper is changed.

**Steps to reproduce it**

Refer screenshots.

**Screenshots of the issue**

whatsapp image 2016-12-30 at 9 54 55 pm 2
whatsapp image 2016-12-30 at 9 54 55 pm 3
whatsapp image 2016-12-30 at 9 54 55 pm 4
whatsapp image 2016-12-30 at 9 54 55 pm 5
whatsapp image 2016-12-30 at 9 54 55 pm 6
whatsapp image 2016-12-30 at 9 54 55 pm 7
whatsapp image 2016-12-30 at 9 54 55 pm 1

**Would you like to work on the issue?**
Yes, I have started working on the issue. will send a PR after admin approval.

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #446 : Wallpaper can now be selected using Google photos

Changes: Previously, the wallpaper selection using Google photos gave an error message "Unable to load image". Now it can be selected using the Google photos app. What i have tried is writing to temp file and return temp image URI, if it has authority in content URI.

Screen shots for the change:  
ezgif com-d1d4b3b856

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package org.fossasia.susi.ai.activities;
 
 import android.Manifest;
+import android.app.Activity;
```
Comment (Abhi2424shek) [inline app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java]: @anantprsd5 please remove the unwanted import statement it's unused as by @codacy-bot

Comment (anantprsd5) [inline app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java]: @Abhi2424shek Yeah, will fix this asap. But do you have any idea why the circleci is failing?

Comment (Abhi2424shek) [inline app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java]: @anantprsd some errors with java.lang on the login screen there's a long log so i guess you should check it!
