### PR TITLE
Replaced Customer server with custom server

### LINKED ISSUE #1192: Replace "Customer Server" with "Custom Server"
**Actual Behaviour**

Custom Server is wrongly written as Customer Server which can be misleading.

**Expected Behaviour**

It should be "Custom Server"

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #1192 

Changes: changed customer server to custom server

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt [hunk 1]
```diff
@@ -84,8 +84,8 @@ class ForgotPasswordActivity : AppCompatActivity (), IForgotPasswordView {
     }
 
     fun showUrl() {
-        customer_server.setOnClickListener {
-            input_url.visibility = if(customer_server.isChecked) View.VISIBLE else View.GONE
+        custom_server.setOnClickListener {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt]: Change to camel case

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -188,7 +188,7 @@
     <!-- Settings Activity-->
     <string name="Continue">Continue</string>
 
-    <string name="email_id_input">Enter your e-mail ID</string>
+    <string name="email_id_input">Enter your e-mail address</string>
```
Comment (iamareebjamal) [inline app/src/main/res/values/strings.xml]: Irrelevant to PR

File: app/src/main/res/values-hi/strings.xml [hunk 3]
```diff
@@ -185,7 +185,7 @@
     <string name="slide_3_desc">ब्राउज़ करें और अपने पसंदीदा एसयूएसआई एआई कौशल की कोशिश करें</string>
     <string name="slide_4_title">चैट सेटिंग्स</string>
     <string name="slide_4_desc">बेहतर अनुभव के लिए अपनी चैट सेटिंग्स को निजीकृत करें</string>
-    <string name="customer_server">ग्राहक सर्वर</string>
```
Comment (iamareebjamal) [inline app/src/main/res/values-hi/strings.xml]: Check other strings as well

File: app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt (hunk 1 above)
Comment (chiragw15) [reply app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt]: It is not a variable name but a resource id which is directly used as a variable using kotlinx. Should it be changed to camelCase?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt]: Yes, it's kotlin and java convention to use camel case

Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt]: @iamareebjamal should this change be made in a separate PR because we have to make these changes in every activity?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt]: OK
