### PR TITLE
Skill Search Listener

### LINKED ISSUE #1371: Skill Search
**Actual Behaviour**

Currently while on Skill Listing and searching it has a underline on the text and the the skill is searched only when the searched is clicked.

**Expected Behaviour**

It should be dynamic in nature, like the user types and the skill is searched.
Remove the underline from edit texr

**Steps to reproduce it**

Go to skill listing and then click on search in the toolbar and search a skill.

**LogCat for the issue**

None.

**Would you like to work on the issue?**

Yes

@arundhati24 @batbrain7

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1371 

Changes: Added on textChanged Listener to the Edit text in the toolbar in Skill Activity

Screenshots for the change: 

@arundhati24 @batbrain7 ! Check please

### CODE REVIEW

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 1]
```diff
@@ -5,6 +5,9 @@ import android.content.Intent
 import android.os.Bundle
 import android.support.v4.content.ContextCompat
 import android.support.v7.app.AppCompatActivity
+import android.text.Editable
+import android.text.TextWatcher
+import android.util.Log
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Where is this being used?

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @arundhati24 I have remove Log, Rest Editable and TextWatcher are used at line 134, 143.

**Comment by codedsun** [comment]
@arundhati24 I  applied a check, that when u enter a state when their are no skills, then we keep the value of check = false and then the search method is not called and when the user deletes the text until the (text) where the skills exist we again called the doSearch method.
That solved the problem of above mentioned.

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 Check that!

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 2]
```diff
@@ -127,13 +127,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(p0: Editable?) {
+                    afterText = p0.toString()
+                    //checking that value exist in skills and if not exist comparing the length of the current text to the previous text where the skills are present
+                    if (check || (afterText.length <= text.length)) {
+                        check = doSearch(p0.toString())
+                        text = p0.toString()
```
Comment (arundhati24) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @codedsun How is this assignment helping? Will the 'text', being a local variable here, retain this value once the user enters another character in the edit search?
Would you please log the values of 'check' and 'text' and notice the changes, if any, in their values? I think the value of check will be true every time the text is modified in the search bar and it would be the same procedure happening as before. Please correct me if I am wrong, but, this is what I see.

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @arundhati24 It does work, the values of local variable are retained and as the case stated above, like you said when u enter arbitary string of infinite length, then also we were calling the doSearch function.

>Here's what I did, I assigned variables (text, afterText, check)
the check value is set to true for first time pass and text and afterText are empty strings.

For the above logic,
First pass 
>- check = true.
     afterText = text that user enters after every keyboard length, 
     and then doSearch on that text, if that returns true, we move to 2nd pass. else we got check to false and text = until where we were' getting the response to true.

So then for pass 2 if user types an extra length query for which no answer exist, check becomes false and we are saved from calling the function.
and when the user deletes or truncates the string to a shorter length which is less than or equal to the value of text we again call doSearch.


Example : Input Suneet and their is a skill named susi.

1. User enters 'S' check = true, doSearch return true, text = S (afterText = S)
2 User enters 'U' check = true, doSearch return true, text = SU (afterText = S)
3.User enters 'N' check = true, doSearch return false, text = 'SUN' (afterText='SUN')
4. Now user enters anything SUNEET, check has become to false and afterText.length > text.length

5. If user truncates some of the words, and like he typed the query SUNEET and then deletes and come backs to SUN, SU,S the doSearch function  is called again.

**Comment by Orbiter** [comment]
@codedsun Please check requested changes

**Comment by codedsun** [comment]
@Orbiter I did already! Please check!

**Comment by codedsun** [comment]
@batbrain7 all checks have passed! which issue you are pointing here?

**Comment by codedsun** [comment]
@arundhati24 We shall proceed with it, if their are no issues.

**Comment by batbrain7** [comment]
@codedsun before the codacy issues present on syncing the branch the checks have passed

**Comment by codedsun** [comment]
@iamareebjamal @arundhati24 Please check this!

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 3]
```diff
@@ -127,13 +127,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
-                if (actionId == EditorInfo.IME_ACTION_SEARCH) {
-                    doSearch((findViewById(R.id.edtSearch) as EditText).text.toString())
-                    return@OnEditorActionListener true
+            //this is a listener to do a search when users enters query in editText
+            edtSearch?.addTextChangedListener(object : TextWatcher {
+                /**
+                 * Variable used to remove unneccessary invoking of doSearch() method.
+                 */
+                var text: String = ""
+                var afterText: String = ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: afterText can be removed from here

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 4]
```diff
@@ -127,13 +127,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(p0: Editable?) {
+                    afterText = p0.toString()
+                    //checking that value exist in skills and if not exist comparing the length of the current text to the previous text where the skills are present
+                    if (check || (afterText.length <= text.length)) {
+                        check = doSearch(p0.toString())
+                        text = p0.toString()
+                    } else Toast.makeText(baseContext, R.string.skill_not_found, Toast.LENGTH_SHORT).show()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Java Style Guideline

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 5]
```diff
@@ -127,13 +127,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                var check = true
+                override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
+                    //no need to implement
+                }
+
+                override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(p0: Editable?) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Name parameter appropriately

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 3 above)
Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @iamareebjamal Where to add then?

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 5 above)
Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @iamareebjamal These were auto generated by Studio.

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Shall I change them?

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Yes

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Locally

**Comment by codedsun** [comment]
@iamareebjamal Check this and merge!

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 Check and merge!

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 6]
```diff
@@ -38,6 +38,7 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
     private var mSearchAction: MenuItem? = null
     private var isSearchOpened = false
     private var edtSearch: EditText? = null
+    private var afterText: String = ""
```
[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: No need of this variable

**Comment by codedsun** [comment]
@batbrain7 It's made so that, the searches are made when the user presses a backspace! If we remove it then the value of *check* will never be changed.

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 7]
```diff
@@ -39,6 +39,8 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
     private var mSearchAction: MenuItem? = null
     private var isSearchOpened = false
     private var edtSearch: EditText? = null
+    var text: String = ""
+    var afterText: String = ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: This variable can be local, I still have no idea why is this global?

Please tell me the amount of places this variable is used and if there is only one coding block where this is being used, then please make this local as I've requested

Also, please tell me where is this modified, if it is not modified since the declaration, make this immutable

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 8]
```diff
@@ -128,13 +128,32 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
+                    //no need to implement
+                }
+
+                override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(s: Editable?) {
+                    afterText = s.toString()
```
[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: This is declaration, not modification. Please understand the difference. Show me two places where `afterText` is being modified

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 9]
```diff
@@ -128,13 +128,33 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
             edtSearch = action.customView.findViewById(R.id.edtSearch) as EditText //the text editor
 
-            //this is a listener to do a search when the user clicks on search button
-            edtSearch?.setOnEditorActionListener(TextView.OnEditorActionListener { v, actionId, event ->
-                if (actionId == EditorInfo.IME_ACTION_SEARCH) {
-                    doSearch((findViewById(R.id.edtSearch) as EditText).text.toString())
-                    return@OnEditorActionListener true
+            //this is a listener to do a search when users enters query in editText
+            edtSearch?.addTextChangedListener(object : TextWatcher {
+                var text: String = ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Make this global

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 10]
```diff
@@ -128,13 +128,33 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                var afterText: String = ""
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Not needed

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: You are doing this

```Kotlin
var i = 0

// Ten classes and 1005 lines later
override fun blah() {
  i = getCount()
  if (i == 10) {
    // Do something
  }
}
```
Why not this, which is sane and does not need 15 global variables which is not even needed in the first place
```Kotlin
// Ten classes and 1005 lines later
override fun blah() {
  val i = getCount()
  if (i == 10) {
    // Do something
  }
}
```

Or even better 
```Kotlin
// Ten classes and 1005 lines later
override fun blah() {
  if (i == getCount()) {
    // Do something
  }
}
```

[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @arundhati24 @batbrain7 If you are able to understand what I am trying to say, please help

[the remark this answers is not in the document]
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Also, you have used `s.toString()` in 3 places even when `afterText` == `s.toString()`

I have a hard time understanding why have you even used the afterText variable when it is exactly same as `s.toString()`

You can completely eliminate the variable and continue using `s.toString()` or just declare a local val `afterText` and remove all reference to `s.toString()`

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 11]
```diff
@@ -147,22 +167,24 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
         }
     }
 
-    fun doSearch(query: String) {
+    //Used to perform search for the query entered by the user
+    fun doSearch(query: String): Boolean {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Rename the function to tell what it's doing, `doSearch` sounds like a void function. What does the boolean returning signify. You have added a comment which does not explain this. The comment is obvious that this performs search, we can see that from the function name

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (batbrain7) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Yes @iamareebjamal I get your point , I made these mistakes as well , if we should not declare unnecessary variables and if a variable is  not used other than inside a particular code block that variable should be made local.

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 12]
```diff
@@ -128,13 +128,33 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
-                    doSearch((findViewById(R.id.edtSearch) as EditText).text.toString())
-                    return@OnEditorActionListener true
+            //this is a listener to do a search when users enters query in editText
+            edtSearch?.addTextChangedListener(object : TextWatcher {
+                var text: String = ""
+                var afterText: String = ""
+                /**
+                 * Variable used to remove unneccessary invoking of doSearch() method.
+                 */
+                var check = true
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Name this better

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 9 above)
Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: prevSearchQuery

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 13]
```diff
@@ -172,6 +195,7 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
 
     fun hideKeyboard() {
         val inputManager: InputMethodManager = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
+        inputManager.hideSoftInputFromWindow(currentFocus.windowToken, InputMethodManager.SHOW_FORCED)
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: this line is below the currentFocus

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 14]
```diff
@@ -147,22 +165,27 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
         }
     }
 
-    fun doSearch(query: String) {
+    /*
+     Used to perform search for the query entered by the user
+     Returns true if the skill is found related to search query else false
+     */
+    fun doSearch(query: String): Boolean {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: rename

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 15]
```diff
@@ -128,13 +129,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
-            edtSearch?.setOnEditorActionListener(TextView.OnEditorActionListener { v, actionId, event ->
-                if (actionId == EditorInfo.IME_ACTION_SEARCH) {
-                    doSearch((findViewById(R.id.edtSearch) as EditText).text.toString())
-                    return@OnEditorActionListener true
+            //this is a listener to do a search when users enters query in editText
+            edtSearch?.addTextChangedListener(object : TextWatcher {
+                /**
+                 * Variable used to remove unneccessary invoking of doSearch() method.
+                 */
+                var searchCheck = true
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: rename

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 16]
```diff
@@ -128,13 +129,30 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                    //no need to implement
+                }
+
+                override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(s: Editable?) {
+                    //checking that value exist in skills and if not exist comparing the length of the current text to the previous text where the skills are present
+                    if (searchCheck || (s.toString().length <= text.length)) {
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Store s.toString in one variable and reuse

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 17]
```diff
@@ -128,13 +128,31 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
-            edtSearch?.setOnEditorActionListener(TextView.OnEditorActionListener { v, actionId, event ->
-                if (actionId == EditorInfo.IME_ACTION_SEARCH) {
-                    doSearch((findViewById(R.id.edtSearch) as EditText).text.toString())
-                    return@OnEditorActionListener true
+            //this is a listener to do a search when users enters query in editText
+            edtSearch?.addTextChangedListener(object : TextWatcher {
+                /**
+                 * Variable used to remove unneccessary invoking of doSearch() method.
+                 */
+                var searchResult = true
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: skillFound

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 18]
```diff
@@ -128,13 +128,31 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
...
+                override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
+                    //no need to implement
+                }
+
+                override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
+                    //no need to implement
+                }
+
+                override fun afterTextChanged(s: Editable?) {
+                    var currentText = s.toString()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: Immutable

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt [hunk 19]
```diff
@@ -40,6 +39,7 @@ class SkillsActivity : AppCompatActivity(), SkillFragmentCallback {
     private var isSearchOpened = false
     private var edtSearch: EditText? = null
     private var skills: ArrayList<Pair<String, List<SkillData>>> = ArrayList()
+    var text: String = ""
```
Comment (batbrain7) [inline app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: make this local , no need for this to be global

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @batbrain7 I made it earlier, I was asked to make it global!

**Comment by codedsun** [comment]
@arundhati24 Please check the PR!

File: app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt (hunk 19 above)
Comment (arundhati24) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @codedsun Why not a private var?

Comment (codedsun) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: @arundhati24 I was asked to make it global earlier as far as I remember!

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt]: This can still be private, global doesn't mean public

**Comment by codedsun** [comment]
@arundhati24 check and then forward to the mentor for review!
